package com.github.chessdork.smogon.models;


public enum Item {
    ABOMASITE("Abomasite", "Mega-evolves Abomasnow."),
    ABSOLITE("Absolite", "Mega-evolves Absol."),
    ABSORB_BULB("Absorb Bulb", "Boosts Special Attack of holder if hit by a Water-type attack. One-time use."),
    ADAMANT_ORB("Adamant Orb", "Hold item which raises power of Dialga's STAB moves by 20%."),
    AERODACTYLITE("Aerodactylite", "Mega-evolves Aerodactyl."),
    AGGRONITE("Aggronite", "Mega-evolves Aggron."),
    AGUAV_BERRY("Aguav Berry", "Restores 1/8 of max HP when at 50% HP or less. One-time use."),
    AIR_BALLOON("Air Balloon", "Makes the holder immune to Ground-type attacks. Disappears when holder is hit."),
    ALAKAZITE("Alakazite", "Mega-evolves Alakazam."),
    AMPHAROSITE("Ampharosite", "Mega-evolves Ampharos."),
    APICOT_BERRY("Apicot Berry", "Raises Special Defense by one stage when at 25% HP or less. One-time use."),
    ASPEAR_BERRY("Aspear Berry", "Cures freeze. One-time use."),
    ASSAULT_VEST("Assault Vest", "Holder's Sp. Def is 1.5x, but it can only use damaging moves."),
    BABIRI_BERRY("Babiri Berry", "Reduces damage from a super effective Steel-type attack by 50%. Consumed after use."),
    BANETTITE("Banettite", "Mega-evolves Banette."),
    BERRY("Berry", "Restores 10 HP when at 50% HP or less. One-time use."),
    BERRY_JUICE("Berry Juice", "Restores 20 HP when at 50% HP or less. One-time use."),
    BERSERK_GENE("Berserk Gene", "Raises Attack, but causes confusion. One-time use."),
    BIG_ROOT("Big Root", "Increases HP gained from draining moves by 30%."),
    BINDING_BAND("Binding Band", "Increases power of multi-turn trapping moves."),
    BITTER_BERRY("Bitter Berry", "Cures confusion. One-time use."),
    BLACK_BELT("Black Belt", "Raises power of Fighting-type moves by 10%."),
    BLACK_SLUDGE("Black Sludge", "Recovers 1/16 of max HP each turn for Poison-types. Damages all other types by 1/8 of max HP each turn."),
    BLACKGLASSES("BlackGlasses", "Raises power of Dark-type moves by 10%."),
    BLASTOISINITE("Blastoisinite", "Mega-evolves Blastoise."),
    BLAZIKENITE("Blazikenite", "Mega-evolves Blaziken."),
    BRIGHTPOWDER("BrightPowder", "Raises evasion by 10%."),
    BUG_GEM("Bug Gem", "Raises the power of a Bug-type move by 50%. One-time use."),
    BURN_DRIVE("Burn Drive", "Changes the type of Techno Blast to Fire."),
    CELL_BATTERY("Cell Battery", "Boosts Attack of holder if hit by an Electric-type attack. One-time use."),
    CHARCOAL("Charcoal", "Raises power of Fire-type moves by 10%."),
    CHARIZARDITE_X("Charizardite X", "Mega-evolves Charizard into Mega Charizard X."),
    CHARIZARDITE_Y("Charizardite Y", "Mega-evolves Charizard into Mega Charizard Y."),
    CHARTI_BERRY("Charti Berry", "Reduces damage from a super effective Rock-type attack by 50%. Consumed after use."),
    CHERI_BERRY("Cheri Berry", "Cures paralysis. One-time use."),
    CHESTO_BERRY("Chesto Berry", "Cures sleep. One-time use."),
    CHILAN_BERRY("Chilan Berry", "Berry blended to make Pokéblocks."),
    CHILL_DRIVE("Chill Drive", "Changes the type of Techno Blast to Ice."),
    CHOICE_BAND("Choice Band", "Raises Attack by 50%, but locks the user into one move."),
    CHOICE_SCARF("Choice Scarf", "Hold item which raises Speed by 50%, but locks holder into one move."),
    CHOICE_SPECS("Choice Specs", "Hold item which raises Special Attack by 50%, but locks holder into one move."),
    CHOPLE_BERRY("Chople Berry", "Reduces damage from a super effective Fighting-type attack by 50%. Consumed after use."),
    CLEANSE_TAG("Cleanse Tag", "Decreases the appearance of wild Pokémon."),
    COBA_BERRY("Coba Berry", "Reduces damage from a super effective Flying-type attack by 50%. Consumed after use."),
    COLBUR_BERRY("Colbur Berry", "Reduces damage from a super effective Dark-type attack by 50%. Consumed after use."),
    CUSTAP_BERRY("Custap Berry", "Activates at 25% HP. Next move used goes first. One-time use."),
    DAMP_ROCK("Damp Rock", "Rain Dance and Drizzle lasts 8 turns."),
    DARK_GEM("Dark Gem", "Raises the power of a Dark-type move by 50%. One-time use."),
    DARK_GLASSES("Dark Glasses", "A hold item that boosts Dark-type moves by 10%."),
    DEEPSEASCALE("DeepSeaScale", "Doubles Clamperl's Special Defense."),
    DEEPSEATOOTH("DeepSeaTooth", "Doubles Clamperl's Special Attack."),
    DESTINY_KNOT("Destiny Knot", "If the holder becomes infatuated, so does the enemy."),
    DOUSE_DRIVE("Douse Drive", "Changes the type of Techno Blast to Water."),
    DRACO_PLATE("Draco Plate", "Raises power of Dragon-type moves by 20%. Pokemon with Multitype become Dragon-type."),
    DRAGON_FANG("Dragon Fang", "Raises power of Dragon-type moves by 10%."),
    DRAGON_GEM("Dragon Gem", "Raises the power of a Dragon-type move by 50%. One-time use."),
    DREAD_PLATE("Dread Plate", "Raises power of the holder's Dark-type moves by 20%. Pokemon with Multitype become Dark-type."),
    EARTH_PLATE("Earth Plate", "Raises power of Ground-type moves by 20%. Pokemon with Multitype become Ground-type."),
    EJECT_BUTTON("Eject Button", "When the holder is hit, it immediately switches out. One-time use."),
    ELECTRIC_GEM("Electric Gem", "Raises the power of a Electric-type move by 50%. One-time use."),
    ENIGMA_BERRY("Enigma Berry", "Pokéblock ingredient. Restores 1/4 of the max HP when hit by a super effective move. One-time use."),
    EVIOLITE("Eviolite", "Boosts Defense and Special Defense of holder by 50% if it is an NFE Pokemon."),
    EXPERT_BELT("Expert Belt", "Super effective attacks are 20% stronger."),
    FIGHTING_GEM("Fighting Gem", "Raises the power of a Fighting-type move by 50%. One-time use."),
    FIGY_BERRY("Figy Berry", "Restores 1/8 max HP when at 50% HP or less. One-time use."),
    FIRE_GEM("Fire Gem", "Raises the power of a Fire-type move by 50%. One-time use."),
    FIST_PLATE("Fist Plate", "Raises power of Fighting-type moves 20%. Pokemon with Multitype become Fighting-type."),
    FLAME_ORB("Flame Orb", "Burns the holder."),
    FLAME_PLATE("Flame Plate", "Raises power of Fire-type moves 20%. Pokemon with Multitype become Fire-type."),
    FLOAT_STONE("Float Stone", "The weight of the holder is halved."),
    FLYING_GEM("Flying Gem", "Raises the power of a Flying-type move by 50%. One-time use."),
    FOCUS_BAND("Focus Band", "Gives an 11.7% chance of surviving a hit with at least 1 HP."),
    FOCUS_SASH("Focus Sash", "The holder always survives one attack. One-time use."),
    FULL_INCENSE("Full Incense", "Makes the holder move last."),
    GANLON_BERRY("Ganlon Berry", "Raises Defense by one stage when at 25% HP or less. One-time use."),
    GARCHOMPITE("Garchompite", "Mega-evolves Garchomp."),
    GARDEVOIRITE("Gardevoirite", "Mega-evolves Gardevoir."),
    GENGARITE("Gengarite", "Mega-evolves Gengar."),
    GHOST_GEM("Ghost Gem", "Raises the power of a Ghost-type move by 50%. One-time use."),
    GOLD_BERRY("Gold Berry", "Restores 30 HP when at 50% HP or less. One-time use."),
    GRASS_GEM("Grass Gem", "Raises the power of a Grass-type move by 50%. One-time use."),
    GRIP_CLAW("Grip Claw", "Partial trapping moves last 6 turns."),
    GRISEOUS_ORB("Griseous Orb", "Raises the power of Giratina's STAB moves 20%. May only be held by Giratina, transforms Giratina into Giratina-O when held. Cannot be removed in battle."),
    GROUND_GEM("Ground Gem", "Raises the power of a Ground-type move by 50%. One-time use."),
    GYARADOSITE("Gyaradosite", "Mega-evolves Gyarados."),
    HABAN_BERRY("Haban Berry", "Reduces damage from a super effective Dragon-type attack by 50%. Consumed after use."),
    HARD_ROCK("Hard Rock", "Raises power of Rock-type moves by 12.5%."),
    HARD_STONE("Hard Stone", "Raises power of Rock-type moves by 10%."),
    HEAT_ROCK("Heat Rock", "Sunny Day and Drought lasts 8 turns."),
    HERACRONITE("Heracronite", "Mega-evolves Heracross."),
    HOUNDOOMINITE("Houndoominite", "Mega-evolves Houndoom."),
    IAPAPA_BERRY("Iapapa Berry", "Restores 1/8 of max HP when at 50% HP or less. One-time use."),
    ICE_BERRY("Ice Berry", "Cures burn. One-time use."),
    ICE_GEM("Ice Gem", "Raises the power of a Ice-type move by 50%. One-time use."),
    ICICLE_PLATE("Icicle Plate", "Raises power of Ice-type moves 20%. Pokemon with Multitype become Ice-type."),
    ICY_ROCK("Icy Rock", "Hail and Snow Warning lasts 8 turns."),
    INSECT_PLATE("Insect Plate", "Raises power of Bug-type moves by 20%. Pokemon with Multitype become Bug-type."),
    IRON_BALL("Iron Ball", "Reduces Speed by 50%."),
    IRON_PLATE("Iron Plate", "Raises power of Steel-type moves by 20%. Pokemon with Multitype become Steel-type."),
    JABOCA_BERRY("Jaboca Berry", "If hit by a physical attack, the attacker takes 12.5% damage. One-time use."),
    KANGASKHANITE("Kangaskhanite", "Mega-evolves Kangaskhan."),
    KASIB_BERRY("Kasib Berry", "Reduces damage from a super effective Ghost-type attack by 50%. Consumed after use."),
    KEBIA_BERRY("Kebia Berry", "Reduces damage from a super effective Poison-type attack by 50%. Consumed after use."),
    KEE_BERRY("Kee Berry", "Raises Defense by 1 stage if hit by a Physical attack. Single use."),
    KELPSY_BERRY("Kelpsy Berry", "Pokéblock ingredient. Plant in loamy soil to grow a Kelpsy plant."),
    KINGS_ROCK("King's Rock", "Moves recieve a 10% flinch chance, if they do not have one already."),
    LAGGING_TAIL("Lagging Tail", "Makes the holder move last."),
    LANSAT_BERRY("Lansat Berry", "Raises critical hit rate by two stages when at 25% HP or less. One-time use."),
    LAX_INCENSE("Lax Incense", "Raises evasion by 5%."),
    LEFTOVERS("Leftovers", "Heals 1/16 of max HP each turn."),
    LEPPA_BERRY("Leppa Berry", "Restores 10 PP to a move that has run out of PP. One-time use."),
    LIECHI_BERRY("Liechi Berry", "Raises Attack by one stage when at 25% HP or less. One-time use."),
    LIFE_ORB("Life Orb", "Boosts power by 30%, user takes 10% recoil each turn it attacks."),
    LIGHT_BALL("Light Ball", "Doubles Pikachu's Special Attack."),
    LIGHT_CLAY("Light Clay", "Reflect and Light Screen last 8 turns."),
    LUCARIONITE("Lucarionite", "Mega-evolves Lucario."),
    LUCKY_PUNCH("Lucky Punch", "Raises Chansey's critical hit ratio by two stages."),
    LUM_BERRY("Lum Berry", "Cures status. One-time use."),
    LUMINOUS_MOSS("Luminous Moss", "Raises Special Defense by 1 stage if hit by a Water-type attack. Single use."),
    LUSTROUS_ORB("Lustrous Orb", "Raises power of Palkia's STAB moves by 20%."),
    MACHO_BRACE("Macho Brace", "Reduces Speed by 50%. Doubles EVs gained."),
    MAGMARIZER("Magmarizer", "Evolves Magmar into Magmortar."),
    MAGNET("Magnet", "Raises power of Electric-type moves 10%."),
    MAGO_BERRY("Mago Berry", "Restores 1/8 max HP when at 50% HP or less. One-time use."),
    MAIL("Mail", "Prevents Trick from working."),
    MANECTITE("Manectite", "Mega-evolves Manectric."),
    MARANGA_BERRY("Maranga Berry", "Raises Special Defense by 1 stage if hit by a Special attack. Single use."),
    MAWILITE("Mawilite", "Mega-evolves Mawile."),
    MEADOW_PLATE("Meadow Plate", "Raises power of Grass-type moves 20%. Pokemon with Multitype become Grass-type."),
    MEDICHAMITE("Medichamite", "Mega-evolves Medicham."),
    MENTAL_HERB("Mental Herb", "Cures infatuation. One-time use."),
    METAL_COAT("Metal Coat", "Raises power of Steel-type moves by 10%."),
    METAL_POWDER("Metal Powder", "Raises Ditto's Defense and Special Defense by 50%."),
    METRONOME("Metronome", "Boost the power of attacks used consecutively."),
    MEWTWONITE_X("Mewtwonite X", "Mega-evolves Mewtwo into Mega Mewtwo X."),
    MEWTWONITE_Y("Mewtwonite Y", "Mega-evolves Mewtwo into Mega Mewtwo Y."),
    MICLE_BERRY("Micle Berry", "The next move used will always hit."),
    MIND_PLATE("Mind Plate", "Raises power of Psychic-type moves by 20%. Pokemon with Multitype become Psychic-type."),
    MINT_BERRY("Mint Berry", "Cures sleep. One-time use."),
    MIRACLE_BERRY("Miracle Berry", "Cures status. One-time use."),
    MIRACLE_SEED("Miracle Seed", "Raises power of Grass-type moves by 10%."),
    MUSCLE_BAND("Muscle Band", "Raises power of physical moves by 10%."),
    MYSTERY_BERRY("Mystery Berry", "Restores 5 PP to a move that has run out of PP. One-time use."),
    MYSTIC_WATER("Mystic Water", "Raises power of Water-type moves by 10%."),
    NEVERMELTICE("NeverMeltIce", "Raises power of Ice-type moves by 10%."),
    NORMAL_GEM("Normal Gem", "Raises the power of a Normal-type move by 50%. One-time use."),
    OCCA_BERRY("Occa Berry", "Reduces damage from a super effective Fire-type attack by 50%. Consumed after use."),
    ODD_INCENSE("Odd Incense", "Raises power of Psychic-type moves by 20%."),
    ORAN_BERRY("Oran Berry", "Restores 10 HP when at 50% HP or less. One-time use."),
    PASSHO_BERRY("Passho Berry", "Reduces damage from a super effective Water-type attack by 50%. Consumed after use."),
    PAYAPA_BERRY("Payapa Berry", "Reduces damage from a super effective Psychic-type attack by 50%. Consumed after use."),
    PECHA_BERRY("Pecha Berry", "Cures poison. One-time use."),
    PERSIM_BERRY("Persim Berry", "Cures confusion. One-time use."),
    PETAYA_BERRY("Petaya Berry", "Raises Special Attack by one stage when at 25% HP or less. One-time use."),
    PINK_BOW("Pink Bow", "Raises power of Normal moves by 10%."),
    PINSIRITE("Pinsirite", "Mega-evolves Pinsir."),
    PIXIE_PLATE("Pixie Plate", "Holder's Fairy-type attacks have 1.2x power. Judgment is Fairy-type."),
    POISON_BARB("Poison Barb", "Raises power of Poison-type moves by 10%."),
    POISON_GEM("Poison Gem", "Raises the power of a Poison-type move by 50%. One-time use."),
    POLKA_DOT_BOW("Polka Dot Bow", "Raises power of Normal moves by 12.5%."),
    POWER_ANKLET("Power Anklet", "Reduces Speed by 50%. Grants 4 Speed EVs when the opponent is defeated. Passes down the Speed IV to its offspring in HGSS."),
    POWER_BAND("Power Band", "Reduces Speed by 50%. Grants 4 Special Defense EVs when the opponent is defeated. Passes down the Special Defense IV to its offspring in HGSS."),
    POWER_BELT("Power Belt", "Reduces Speed by 50%. Grants 4 Defense EVs when the opponent is defeated. Passes down the Defense IV to its offspring in HGSS."),
    POWER_BRACER("Power Bracer", "Reduces Speed by 50%. Grants 4 Attack EVs when the opponent is defeated. Passes down the Attack IV to its offspring in HGSS."),
    POWER_HERB("Power Herb", "Removes the charge up turn from all moves. One-time use."),
    POWER_LENS("Power Lens", "Reduces Speed by 50%. Grants 4 Special Attack EVs when the opponent is defeated. Passes down it's Special Attack IV to its offspring in HGSS."),
    POWER_WEIGHT("Power Weight", "Reduces Speed by 50%. Grants 4 HP EVs when the opponent is defeated. Passes down HP IV to its offspring in HGSS."),
    PRZCURE_BERRY("PRZCure Berry", "Cures paralysis. One-time use."),
    PSNCURE_BERRY("PSNCure Berry", "Cures poison. One-time use."),
    PSYCHIC_GEM("Psychic Gem", "Raises the power of a Psychic-type move by 50%. One-time use."),
    QUICK_CLAW("Quick Claw", "Gives the user a 23.4375% chance to go first."),
    QUICK_POWDER("Quick Powder", "Doubles Ditto's Speed."),
    RAWST_BERRY("Rawst Berry", "Cures burn. One-time use."),
    RAZOR_CLAW("Razor Claw", "Raises critical hit rate by one stage."),
    RAZOR_FANG("Razor Fang", "Certain moves have a 10% flinch rate."),
    RED_CARD("Red Card", "The opponent is forced out immediately if it attacks the holder. One-time use."),
    RINDO_BERRY("Rindo Berry", "Reduces damage from a super effective Grass-type attack by 50%. Consumed after use."),
    ROCK_GEM("Rock Gem", "Raises the power of a Rock-type move by 50%. One-time use."),
    ROCK_INCENSE("Rock Incense", "Raises power of Rock-type moves by 20%."),
    ROCKY_HELMET("Rocky Helmet", "Damages the opponent for 1/6 of max HP when the opponent makes contact."),
    ROSE_INCENSE("Rose Incense", "Raises power of Grass-type moves by 20%."),
    ROSELI_BERRY("Roseli Berry", "Halves damage taken from a super effective Fairy-type attack. Single use."),
    ROWAP_BERRY("Rowap Berry", "If hit by a special attack, the attacker takes 12.5% damage. One-time use."),
    SAFETY_GOGGLES("Safety Goggles", "Protects the holder from weather-related damage and powder moves."),
    SALAC_BERRY("Salac Berry", "Raises Speed by one stage when at 25% HP or less. One-time use."),
    SCIZORITE("Scizorite", "Mega-evolves Scizor."),
    SCOPE_LENS("Scope Lens", "Raises critical hit rate by one stage."),
    SEA_INCENSE("Sea Incense", "Raises power of Water-type moves 5%."),
    SHARP_BEAK("Sharp Beak", "Raises power of Flying-type moves 10%."),
    SHED_SHELL("Shed Shell", "Allows holder to switch out even when trapped."),
    SHELL_BELL("Shell Bell", "Heals this Pokemon for 1/8 of the damage it does."),
    SHOCK_DRIVE("Shock Drive", "Changes the type of Techno Blast to Electric."),
    SHUCA_BERRY("Shuca Berry", "Reduces damage from a super effective Ground-type attack by 50%. Consumed after use."),
    SILK_SCARF("Silk Scarf", "Raises power of Normal-type moves by 10%."),
    SILVERPOWDER("SilverPowder", "Raises power of Bug-type moves by 10%."),
    SITRUS_BERRY("Sitrus Berry", "Restores 1/4 of the max HP when at 1/2 HP or less. One-time use."),
    SKY_PLATE("Sky Plate", "Raises power of Flying-type moves by 20%. Pokemon with Multitype become Flying-type."),
    SMOOTH_ROCK("Smooth Rock", "Makes Sandstorm and Sand Stream last 8 turns."),
    SNOWBALL("Snowball", "Raises Attack by 1 stage if hit by an Ice-type attack. Single use."),
    SOFT_SAND("Soft Sand", "Raises power of Ground-type moves by 10%."),
    SOUL_DEW("Soul Dew", "Raises Special Attack and Special Defense of Latias and Latios by 50%."),
    SPELL_TAG("Spell Tag", "Raises power of Ghost-type moves by 10%."),
    SPLASH_PLATE("Splash Plate", "Raises power of Water-type moves by 20%. Pokemon with Multitype become Water-type."),
    SPOOKY_PLATE("Spooky Plate", "Raises power of Ghost-type moves by 20%. Pokemon with Multitype become Ghost-type."),
    STARF_BERRY("Starf Berry", "Raises a stat by two stages when at 25% HP or less. One-time use."),
    STEEL_GEM("Steel Gem", "Raises the power of a Steel-type move by 50%. One-time use."),
    STICK("Stick", "Raises Farfetch'd's critical hit ratio by two stages."),
    STICKY_BARB("Sticky Barb", "Causes damage to holder and attaches to attacker upon contact."),
    STONE_PLATE("Stone Plate", "Raises base power of Rock-type moves by 20%. Pokemon with Multitype become Rock-type."),
    TANGA_BERRY("Tanga Berry", "Reduces damage from a super effective Bug-type attack by 50%. Consumed after use."),
    THICK_CLUB("Thick Club", "Doubles Cubone's and Marowak's Attack."),
    TOXIC_ORB("Toxic Orb", "Badly poisons the holder."),
    TOXIC_PLATE("Toxic Plate", "Raises power of Poison-type moves by 20%. Pokemon with Multitype become Poison-type."),
    TWISTEDSPOON("TwistedSpoon", "Raises power of Psychic moves by 10%."),
    TYRANITARITE("Tyranitarite", "Mega-evolves Tyranitar."),
    VENUSAURITE("Venusaurite", "Mega-evolves Venusaur."),
    WACAN_BERRY("Wacan Berry", "Reduces damage from a super effective Electric-type attack by 50%. Consumed after use."),
    WATER_GEM("Water Gem", "Raises the power of a Water-type move by 50%. One-time use."),
    WATER_STONE("Water Stone", "Evolves Eevee, Poliwhirl, Shellder, and Staryu."),
    WAVE_INCENSE("Wave Incense", "Raises power of Water-type moves by 20%."),
    WEAKNESS_POLICY("Weakness Policy", "Attack and Special Attack sharply increase when hit super effectively. Single use."),
    WHITE_HERB("White Herb", "Removes stat decreases. One-time use."),
    WIDE_LENS("Wide Lens", "Raises accuracy by 10%."),
    WIKI_BERRY("Wiki Berry", "Restores 1/8 of max HP when at 50% of max HP or less. One-time use."),
    WISE_GLASSES("Wise Glasses", "Raises damage from special moves by 10%."),
    YACHE_BERRY("Yache Berry", "Reduces damage from a super effective Ice-type attack by 50%. Consumed after use."),
    ZAP_PLATE("Zap Plate", "Raises power of Electric moves by 20%. Pokemon with Multitype become Electric-type."),
    ZOOM_LENS("Zoom Lens", "Raises accuracy by 20% if the holder moves after the target.");

    private final String name, description;

    Item(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public String toString() {
        return name;
    }
}
