package com.github.chessdork.smogon.models;


public enum Move {
    ABSORB("Absorb", PokemonType.GRASS, 100, 20, 25, MoveCategory.SPECIAL, "Leeches 50% damage."),
    ACID("Acid", PokemonType.POISON, 100, 40, 30, MoveCategory.SPECIAL, "10% chance to lower Defense by 1 stage."),
    ACID_ARMOR("Acid Armor", PokemonType.POISON, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Defense by 2 stages."),
    ACID_SPRAY("Acid Spray", PokemonType.POISON, 100, 40, 20, MoveCategory.SPECIAL, "Lowers target's Special Defense by 2 stages."),
    ACROBATICS("Acrobatics", PokemonType.FLYING, 100, 55, 15, MoveCategory.PHYSICAL, "Doubles in power if user has no held item."),
    ACUPRESSURE("Acupressure", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Boosts a random stat by 2 stages."),
    AERIAL_ACE("Aerial Ace", PokemonType.FLYING, 0, 60, 20, MoveCategory.PHYSICAL, "Ignores accuracy modifiers."),
    AEROBLAST("Aeroblast", PokemonType.FLYING, 95, 100, 5, MoveCategory.SPECIAL, "High critical hit rate."),
    AFTER_YOU("After You", PokemonType.NORMAL, 0, 0, 15, MoveCategory.NON_DAMAGING, "The target will attack immediately after the user in the same turn."),
    AGILITY("Agility", PokemonType.PSYCHIC, 0, 0, 30, MoveCategory.NON_DAMAGING, "Boosts Speed by 2 stages."),
    AIR_CUTTER("Air Cutter", PokemonType.FLYING, 95, 60, 25, MoveCategory.SPECIAL, "High critical hit rate."),
    AIR_SLASH("Air Slash", PokemonType.FLYING, 95, 75, 20, MoveCategory.SPECIAL, "High critical hit rate."),
    ALLY_SWITCH("Ally Switch", PokemonType.PSYCHIC, 0, 0, 15, MoveCategory.NON_DAMAGING, "Switches position with another Pokemon on user's side of the field."),
    AMNESIA("Amnesia", PokemonType.PSYCHIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Special Defense by 2 stages."),
    ANCIENT_POWER("Ancient Power", PokemonType.ROCK, 100, 60, 5, MoveCategory.SPECIAL, "10% chance to boost all stats by 1 stage."),
    AQUA_JET("Aqua Jet", PokemonType.WATER, 100, 40, 20, MoveCategory.PHYSICAL, "The user always attacks first."),
    AQUA_RING("Aqua Ring", PokemonType.WATER, 0, 0, 20, MoveCategory.NON_DAMAGING, "User recovers 1/16th of max HP each turn."),
    AQUA_TAIL("Aqua Tail", PokemonType.WATER, 90, 90, 10, MoveCategory.PHYSICAL, "No additional effect."),
    ARM_THRUST("Arm Thrust", PokemonType.FIGHTING, 100, 15, 20, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    AROMATHERAPY("Aromatherapy", PokemonType.GRASS, 0, 0, 5, MoveCategory.NON_DAMAGING, "Cures status on the user's team."),
    AROMATIC_MIST("Aromatic Mist", PokemonType.FAIRY, 100, 0, 20, MoveCategory.NON_DAMAGING, "The user raises the Special Defense stat of itself and ally Pokemon by 1."),
    ASSIST("Assist", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Uses a random move from the user's team."),
    ASSURANCE("Assurance", PokemonType.DARK, 100, 60, 10, MoveCategory.PHYSICAL, "Base Power doubles if the foe takes damage in the same turn, before the attack hits."),
    ASTONISH("Astonish", PokemonType.GHOST, 100, 30, 15, MoveCategory.PHYSICAL, "30% chance to flinch."),
    ATTACK_ORDER("Attack Order", PokemonType.BUG, 100, 90, 15, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    ATTRACT("Attract", PokemonType.NORMAL, 100, 0, 15, MoveCategory.NON_DAMAGING, "Targets of the opposite gender are infatuated and have a 50% chance to do nothing."),
    AURA_SPHERE("Aura Sphere", PokemonType.FIGHTING, 0, 80, 20, MoveCategory.SPECIAL, "Ignores accuracy modifiers."),
    AURORA_BEAM("Aurora Beam", PokemonType.ICE, 100, 65, 20, MoveCategory.SPECIAL, "10% chance to lower Attack by 1 stage."),
    AUTOTOMIZE("Autotomize", PokemonType.STEEL, 0, 0, 15, MoveCategory.NON_DAMAGING, "Boosts user's Speed by 2 stages. Reduces user's weight."),
    AVALANCHE("Avalanche", PokemonType.ICE, 100, 60, 10, MoveCategory.PHYSICAL, "Doubles in power if damaged by the target."),
    BABY_DOLL_EYES("Baby-Doll Eyes", PokemonType.FAIRY, 100, 0, 30, MoveCategory.NON_DAMAGING, "Lowers the target's Attack by 1 stage. Priority +1."),
    BARRAGE("Barrage", PokemonType.NORMAL, 85, 15, 20, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    BARRIER("Barrier", PokemonType.PSYCHIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Defense by 2 stages."),
    BATON_PASS("Baton Pass", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "User switches, but passes on all stat changes and some special conditions."),
    BEAT_UP("Beat Up", PokemonType.DARK, 100, 0, 10, MoveCategory.PHYSICAL, "All healthy Pokemon aid in damaging the target."),
    BELCH("Belch", PokemonType.POISON, 90, 120, 10, MoveCategory.SPECIAL, "The user must eat a Berry to use this move."),
    BELLY_DRUM("Belly Drum", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "User loses 50% of max HP. Maximizes Attack."),
    BESTOW("Bestow", PokemonType.NORMAL, 0, 0, 15, MoveCategory.NON_DAMAGING, "User passes its held item to the target."),
    BIDE("Bide", PokemonType.NORMAL, 0, 0, 10, MoveCategory.PHYSICAL, "Charges for 2-3 turns; returns double the damage received in those turns."),
    BIND("Bind", PokemonType.NORMAL, 85, 15, 20, MoveCategory.PHYSICAL, "Prevents the opponent from attacking for 2-5 turns."),
    BITE("Bite", PokemonType.DARK, 100, 60, 25, MoveCategory.PHYSICAL, "10% chance to flinch."),
    BLAST_BURN("Blast Burn", PokemonType.FIRE, 90, 150, 5, MoveCategory.SPECIAL, "User cannot move next turn."),
    BLAZE_KICK("Blaze Kick", PokemonType.FIRE, 90, 85, 10, MoveCategory.PHYSICAL, "High critical hit rate. 10% chance to burn the target."),
    BLIZZARD("Blizzard", PokemonType.ICE, 70, 110, 5, MoveCategory.SPECIAL, "10% chance to freeze."),
    BLOCK("Block", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "The target cannot switch out."),
    BLUE_FLARE("Blue Flare", PokemonType.FIRE, 85, 130, 5, MoveCategory.SPECIAL, "20% chance to burn the target."),
    BODY_SLAM("Body Slam", PokemonType.NORMAL, 100, 85, 15, MoveCategory.PHYSICAL, "30% chance to paralyze."),
    BOLT_STRIKE("Bolt Strike", PokemonType.ELECTRIC, 85, 130, 5, MoveCategory.PHYSICAL, "20% chance to paralyze the target."),
    BONE_CLUB("Bone Club", PokemonType.GROUND, 85, 65, 20, MoveCategory.PHYSICAL, "10% chance to flinch."),
    BONE_RUSH("Bone Rush", PokemonType.GROUND, 80, 25, 10, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    BONEMERANG("Bonemerang", PokemonType.GROUND, 90, 50, 10, MoveCategory.PHYSICAL, "Hits twice in one turn."),
    BOOMBURST("Boomburst", PokemonType.NORMAL, 100, 140, 10, MoveCategory.SPECIAL, "Deals damage to all Pokemon within range, including any allies."),
    BOUNCE("Bounce", PokemonType.FLYING, 85, 85, 5, MoveCategory.PHYSICAL, "User is made invulnerable for one turn, then hits the next turn. 30% chance to paralyze."),
    BRAVE_BIRD("Brave Bird", PokemonType.FLYING, 100, 120, 15, MoveCategory.PHYSICAL, "Has 1/3 recoil damage."),
    BRICK_BREAK("Brick Break", PokemonType.FIGHTING, 100, 75, 15, MoveCategory.PHYSICAL, "Destroys Light Screen and Reflect, then hits."),
    BRINE("Brine", PokemonType.WATER, 100, 65, 10, MoveCategory.SPECIAL, "Base Power doubles if foe's HP is 50% or less."),
    BUBBLE("Bubble", PokemonType.WATER, 100, 40, 30, MoveCategory.SPECIAL, "10% chance to lower Speed by 1 stage."),
    BUBBLE_BEAM("Bubble Beam", PokemonType.WATER, 100, 65, 20, MoveCategory.SPECIAL, "10% chance to lower Speed by 1 stage."),
    BUG_BITE("Bug Bite", PokemonType.BUG, 100, 60, 20, MoveCategory.PHYSICAL, "Uses foe's Berry."),
    BUG_BUZZ("Bug Buzz", PokemonType.BUG, 100, 90, 10, MoveCategory.SPECIAL, "10% chance to lower Special Defense by 1 stage."),
    BULK_UP("Bulk Up", PokemonType.FIGHTING, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Attack and Defense by 1 stage."),
    BULLDOZE("Bulldoze", PokemonType.GROUND, 100, 60, 20, MoveCategory.PHYSICAL, "Lowers target's Speed by 1 stage."),
    BULLET_PUNCH("Bullet Punch", PokemonType.STEEL, 100, 40, 30, MoveCategory.PHYSICAL, "The user always attacks first."),
    BULLET_SEED("Bullet Seed", PokemonType.GRASS, 100, 25, 30, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    CALM_MIND("Calm Mind", PokemonType.PSYCHIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Special Attack and Special Defense by 1 stage."),
    CAMOUFLAGE("Camouflage", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Changes user's type to Normal in link battles."),
    CAPTIVATE("Captivate", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers an opposite gender foe's Special Attack by 2 stages."),
    CELEBRATE("Celebrate", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "No in-game effect."),
    CHARGE("Charge", PokemonType.ELECTRIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Doubles power of an Electric-type move used next turn."),
    CHARGE_BEAM("Charge Beam", PokemonType.ELECTRIC, 90, 50, 10, MoveCategory.SPECIAL, "70% chance to boost Special Attack by 1 stage."),
    CHARM("Charm", PokemonType.FAIRY, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers foe's Attack by 2 stages."),
    CHATTER("Chatter", PokemonType.FLYING, 100, 65, 20, MoveCategory.SPECIAL, "Confuses the target."),
    CHIP_AWAY("Chip Away", PokemonType.NORMAL, 100, 70, 20, MoveCategory.PHYSICAL, "Ignores the target's stat changes."),
    CIRCLE_THROW("Circle Throw", PokemonType.FIGHTING, 90, 60, 10, MoveCategory.PHYSICAL, "Forces the target to switch to a random Pokemon."),
    CLAMP("Clamp", PokemonType.WATER, 85, 35, 10, MoveCategory.PHYSICAL, "Prevents the opponent from attacking for 2-5 turns."),
    CLEAR_SMOG("Clear Smog", PokemonType.POISON, 0, 50, 15, MoveCategory.SPECIAL, "Eliminates the target's stat changes."),
    CLOSE_COMBAT("Close Combat", PokemonType.FIGHTING, 100, 120, 5, MoveCategory.PHYSICAL, "Lowers user's Defense and Special Defense by 1 stage."),
    COIL("Coil", PokemonType.POISON, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts user's Attack, Defense, and accuracy by 1 stage."),
    COMET_PUNCH("Comet Punch", PokemonType.NORMAL, 85, 18, 15, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    CONFIDE("Confide", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Lowers the target's Special Attack by 1 stage."),
    CONFUSE_RAY("Confuse Ray", PokemonType.GHOST, 100, 0, 10, MoveCategory.NON_DAMAGING, "Confuses the target."),
    CONFUSION("Confusion", PokemonType.PSYCHIC, 100, 50, 25, MoveCategory.SPECIAL, "10% chance to confuse."),
    CONSTRICT("Constrict", PokemonType.NORMAL, 100, 10, 35, MoveCategory.PHYSICAL, "10% chance to lower Speed by 1 stage."),
    CONVERSION("Conversion", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Changes user into the type of its first move."),
    CONVERSION_2("Conversion 2", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Changes user into a new type that resists the last attack to hit the user."),
    COPYCAT("Copycat", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Uses the last move used in the battle."),
    COSMIC_POWER("Cosmic Power", PokemonType.PSYCHIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Defense and Special Defense by 1 stage."),
    COTTON_GUARD("Cotton Guard", PokemonType.GRASS, 0, 0, 10, MoveCategory.NON_DAMAGING, "Boosts user's Defense by 3 stages."),
    COTTON_SPORE("Cotton Spore", PokemonType.GRASS, 100, 0, 40, MoveCategory.NON_DAMAGING, "Lowers foe's Speed by 2 stages."),
    COUNTER("Counter", PokemonType.FIGHTING, 100, 0, 20, MoveCategory.PHYSICAL, "If hit by a physical attack, returns double the damage."),
    COVET("Covet", PokemonType.NORMAL, 100, 60, 25, MoveCategory.PHYSICAL, "Steals target's item."),
    CRABHAMMER("Crabhammer", PokemonType.WATER, 90, 100, 10, MoveCategory.PHYSICAL, "High critical hit rate."),
    CRAFTY_SHIELD("Crafty Shield", PokemonType.FAIRY, 0, 0, 10, MoveCategory.NON_DAMAGING, "Protects the user and allies from status moves. Priority +4."),
    CROSS_CHOP("Cross Chop", PokemonType.FIGHTING, 80, 100, 5, MoveCategory.PHYSICAL, "High critical hit rate."),
    CROSS_POISON("Cross Poison", PokemonType.POISON, 100, 70, 20, MoveCategory.PHYSICAL, "Has a high critical hit rate. 10% chance to poison foe."),
    CRUNCH("Crunch", PokemonType.DARK, 100, 80, 15, MoveCategory.PHYSICAL, "20% chance to lower Special Defense by 1 stage."),
    CRUSH_CLAW("Crush Claw", PokemonType.NORMAL, 95, 75, 10, MoveCategory.PHYSICAL, "50% chance to lower Defense by 1 stage."),
    CRUSH_GRIP("Crush Grip", PokemonType.NORMAL, 100, 0, 5, MoveCategory.PHYSICAL, "Base power depends on the foe's remaining HP."),
    CURSE("Curse", PokemonType.GHOST, 0, 0, 10, MoveCategory.NON_DAMAGING, "Does 1/4 of max HP damage per turn at the cost of half the user's max HP if the user is a Ghost. Boosts Attack and Defense and lowers Speed by 1 stage otherwise."),
    CUT("Cut", PokemonType.NORMAL, 95, 50, 30, MoveCategory.PHYSICAL, "No additional effect."),
    DARK_PULSE("Dark Pulse", PokemonType.DARK, 100, 80, 15, MoveCategory.SPECIAL, "20% chance to flinch."),
    DARK_VOID("Dark Void", PokemonType.DARK, 80, 0, 10, MoveCategory.NON_DAMAGING, "Induces sleep."),
    DAZZLING_GLEAM("Dazzling Gleam", PokemonType.FAIRY, 100, 80, 10, MoveCategory.SPECIAL, "Deals damage to all adjacent foes."),
    DEFEND_ORDER("Defend Order", PokemonType.BUG, 0, 0, 10, MoveCategory.NON_DAMAGING, "Boosts Defense and Special Defense by 1 stage."),
    DEFENSE_CURL("Defense Curl", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "Boosts Defense by 1 stage."),
    DEFOG("Defog", PokemonType.FLYING, 0, 0, 15, MoveCategory.NON_DAMAGING, "Lowers target's evasion by 1 stage. Removes various field effects."),
    DESTINY_BOND("Destiny Bond", PokemonType.GHOST, 0, 0, 5, MoveCategory.NON_DAMAGING, "If the user faints, the foe faints."),
    DETECT("Detect", PokemonType.FIGHTING, 0, 0, 5, MoveCategory.NON_DAMAGING, "Prevents anything from working on the user that turn."),
    DIAMOND_STORM("Diamond Storm", PokemonType.ROCK, 95, 100, 5, MoveCategory.PHYSICAL, "50% chance to boost user's Defense."),
    DIG("Dig", PokemonType.GROUND, 100, 80, 10, MoveCategory.PHYSICAL, "User is made invulnerable for one turn, then hits the next turn."),
    DISABLE("Disable", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Prevents the last move used from being used again for 2-5 turns."),
    DISARMING_VOICE("Disarming Voice", PokemonType.FAIRY, 0, 40, 15, MoveCategory.SPECIAL, "This attack never misses."),
    DISCHARGE("Discharge", PokemonType.ELECTRIC, 100, 80, 15, MoveCategory.SPECIAL, "30% chance to paralyze."),
    DIVE("Dive", PokemonType.WATER, 100, 80, 10, MoveCategory.PHYSICAL, "User is made invulnerable for one turn, then hits the next turn."),
    DIZZY_PUNCH("Dizzy Punch", PokemonType.NORMAL, 100, 70, 10, MoveCategory.PHYSICAL, "20% chance to confuse."),
    DOOM_DESIRE("Doom Desire", PokemonType.STEEL, 100, 140, 5, MoveCategory.SPECIAL, "Deals damage at the end of the turn after three turns."),
    DOUBLE_HIT("Double Hit", PokemonType.NORMAL, 90, 35, 10, MoveCategory.PHYSICAL, "Hits 2 times in one turn."),
    DOUBLE_KICK("Double Kick", PokemonType.FIGHTING, 100, 30, 30, MoveCategory.PHYSICAL, "Hits twice in 1 turn."),
    DOUBLE_SLAP("Double Slap", PokemonType.NORMAL, 85, 15, 10, MoveCategory.PHYSICAL, "Hits 2-5 times in 1 turn."),
    DOUBLE_TEAM("Double Team", PokemonType.NORMAL, 0, 0, 15, MoveCategory.NON_DAMAGING, "Boosts evasion by 1 stage."),
    DOUBLE_EDGE("Double-Edge", PokemonType.NORMAL, 100, 120, 15, MoveCategory.PHYSICAL, "Has 1/3 recoil."),
    DRACO_METEOR("Draco Meteor", PokemonType.DRAGON, 90, 130, 5, MoveCategory.SPECIAL, "Lowers user's Special Attack by 2 stages."),
    DRAGON_BREATH("Dragon Breath", PokemonType.DRAGON, 100, 60, 20, MoveCategory.SPECIAL, "30% chance to paralyze."),
    DRAGON_CLAW("Dragon Claw", PokemonType.DRAGON, 100, 80, 15, MoveCategory.PHYSICAL, "No additional effect."),
    DRAGON_DANCE("Dragon Dance", PokemonType.DRAGON, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Attack and Speed by 1 stage."),
    DRAGON_PULSE("Dragon Pulse", PokemonType.DRAGON, 100, 85, 10, MoveCategory.SPECIAL, "No additional effect."),
    DRAGON_RAGE("Dragon Rage", PokemonType.DRAGON, 100, 0, 10, MoveCategory.SPECIAL, "Always does 40 HP damage."),
    DRAGON_RUSH("Dragon Rush", PokemonType.DRAGON, 75, 100, 10, MoveCategory.PHYSICAL, "20% chance to flinch."),
    DRAGON_TAIL("Dragon Tail", PokemonType.DRAGON, 90, 60, 10, MoveCategory.PHYSICAL, "Forces the target to switch to a random Pokemon."),
    DRAIN_PUNCH("Drain Punch", PokemonType.FIGHTING, 100, 75, 10, MoveCategory.PHYSICAL, "Leeches 50% damage."),
    DRAINING_KISS("Draining Kiss", PokemonType.FAIRY, 100, 50, 10, MoveCategory.SPECIAL, "Deals damage to one adjacent target. The user recovers 75% of the HP lost by the target, rounded up. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down. Makes contact."),
    DREAM_EATER("Dream Eater", PokemonType.PSYCHIC, 100, 100, 15, MoveCategory.SPECIAL, "Leeches 50% of the damage dealt. Only works if target is asleep."),
    DRILL_PECK("Drill Peck", PokemonType.FLYING, 100, 80, 20, MoveCategory.PHYSICAL, "No additional effect."),
    DRILL_RUN("Drill Run", PokemonType.GROUND, 95, 80, 10, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    DUAL_CHOP("Dual Chop", PokemonType.DRAGON, 90, 40, 15, MoveCategory.PHYSICAL, "Hits 2 times in one turn."),
    DYNAMIC_PUNCH("Dynamic Punch", PokemonType.FIGHTING, 50, 100, 5, MoveCategory.PHYSICAL, "Confuses the foe."),
    EARTH_POWER("Earth Power", PokemonType.GROUND, 100, 90, 10, MoveCategory.SPECIAL, "10% chance to lower Special Defense by 1 stage."),
    EARTHQUAKE("Earthquake", PokemonType.GROUND, 100, 100, 10, MoveCategory.PHYSICAL, "Hits Pokemon using Dig with double Base Power."),
    ECHOED_VOICE("Echoed Voice", PokemonType.NORMAL, 100, 40, 15, MoveCategory.SPECIAL, "Power increases when used consecutively."),
    EERIE_IMPULSE("Eerie Impulse", PokemonType.ELECTRIC, 100, 0, 15, MoveCategory.NON_DAMAGING, "Harshly lowers the target's Special Attack stat."),
    EGG_BOMB("Egg Bomb", PokemonType.NORMAL, 75, 100, 10, MoveCategory.PHYSICAL, "No additional effect."),
    ELECTRIC_TERRAIN("Electric Terrain", PokemonType.ELECTRIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "For five turns, Pokemon on the ground cannot fall asleep, and will be woken up if already sleeping. Their Electric-type moves are powered up by 50%."),
    ELECTRIFY("Electrify", PokemonType.ELECTRIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "If the target is electrified before it uses a move during that turn, the target's move becomes Electric type."),
    ELECTRO_BALL("Electro Ball", PokemonType.ELECTRIC, 100, 0, 10, MoveCategory.SPECIAL, "Inflicts more damage the faster the user is compared to the target."),
    ELECTROWEB("Electroweb", PokemonType.ELECTRIC, 95, 55, 15, MoveCategory.SPECIAL, "Lowers target's Speed by 1 stage."),
    EMBARGO("Embargo", PokemonType.DARK, 100, 0, 15, MoveCategory.NON_DAMAGING, "Item use is prevented for five turns."),
    EMBER("Ember", PokemonType.FIRE, 100, 40, 25, MoveCategory.SPECIAL, "10% chance to burn."),
    ENCORE("Encore", PokemonType.NORMAL, 100, 0, 5, MoveCategory.NON_DAMAGING, "Causes the target to repeat the last move for 2-5 turns."),
    ENDEAVOR("Endeavor", PokemonType.NORMAL, 100, 0, 5, MoveCategory.PHYSICAL, "Lowers the target's HP to the user's HP."),
    ENDURE("Endure", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "The user always survives with at least 1 HP."),
    ENERGY_BALL("Energy Ball", PokemonType.GRASS, 100, 90, 10, MoveCategory.SPECIAL, "10% chance to lower Special Defense by 1 stage."),
    ENTRAINMENT("Entrainment", PokemonType.NORMAL, 100, 0, 15, MoveCategory.NON_DAMAGING, "Changes the target's ability to that of the user."),
    ERUPTION("Eruption", PokemonType.FIRE, 100, 150, 5, MoveCategory.SPECIAL, "Does less damage as the user's HP decreases."),
    EXPLOSION("Explosion", PokemonType.NORMAL, 100, 250, 5, MoveCategory.PHYSICAL, "Faints the user."),
    EXTRASENSORY("Extrasensory", PokemonType.PSYCHIC, 100, 80, 20, MoveCategory.SPECIAL, "10% chance to flinch."),
    EXTREME_SPEED("Extreme Speed", PokemonType.NORMAL, 100, 80, 5, MoveCategory.PHYSICAL, "The user always attacks first."),
    FACADE("Facade", PokemonType.NORMAL, 100, 70, 20, MoveCategory.PHYSICAL, "Has 140 Base Power when burned, paralyzed, or poisoned."),
    FAIRY_LOCK("Fairy Lock", PokemonType.FAIRY, 0, 0, 10, MoveCategory.NON_DAMAGING, "Keeps all Pokemon from fleeing during the next turn."),
    FAIRY_WIND("Fairy Wind", PokemonType.FAIRY, 100, 40, 30, MoveCategory.SPECIAL, "Deals damage to one adjacent target."),
    FAKE_OUT("Fake Out", PokemonType.NORMAL, 100, 40, 10, MoveCategory.PHYSICAL, "The user always moves first, and flinches the foe. Can only be used on the first turn out."),
    FAKE_TEARS("Fake Tears", PokemonType.DARK, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers Special Defense by 2 stages."),
    FALSE_SWIPE("False Swipe", PokemonType.NORMAL, 100, 40, 40, MoveCategory.PHYSICAL, "Always leaves the foe with at least 1 HP."),
    FEATHER_DANCE("Feather Dance", PokemonType.FLYING, 100, 0, 15, MoveCategory.NON_DAMAGING, "Lowers Attack 2 stages."),
    FEINT("Feint", PokemonType.NORMAL, 100, 30, 10, MoveCategory.PHYSICAL, "Only works if the foe uses Detect or Protect; nullifies effects of those moves."),
    FEINT_ATTACK("Feint Attack", PokemonType.DARK, 0, 60, 20, MoveCategory.PHYSICAL, "Ignores accuracy modifiers."),
    FELL_STINGER("Fell Stinger", PokemonType.BUG, 100, 30, 25, MoveCategory.PHYSICAL, "When the user knocks out a target with this move, the user's Attack stat rises sharply."),
    FIERY_DANCE("Fiery Dance", PokemonType.FIRE, 100, 80, 10, MoveCategory.SPECIAL, "50% chance to boost user's Special Attack by 1 stage."),
    FINAL_GAMBIT("Final Gambit", PokemonType.FIGHTING, 100, 0, 5, MoveCategory.SPECIAL, "Faints the user. Target takes damage equal to the user's HP at the time of use."),
    FIRE_BLAST("Fire Blast", PokemonType.FIRE, 85, 110, 5, MoveCategory.SPECIAL, "10% chance to burn."),
    FIRE_FANG("Fire Fang", PokemonType.FIRE, 95, 65, 15, MoveCategory.PHYSICAL, "10% chance to flinch. 10% chance to burn."),
    FIRE_PLEDGE("Fire Pledge", PokemonType.FIRE, 100, 80, 10, MoveCategory.SPECIAL, "Use with Grass Pledge and Water Pledge for additional effect."),
    FIRE_PUNCH("Fire Punch", PokemonType.FIRE, 100, 75, 15, MoveCategory.PHYSICAL, "10% chance to burn."),
    FIRE_SPIN("Fire Spin", PokemonType.FIRE, 85, 35, 15, MoveCategory.SPECIAL, "Prevents the opponent from attacking for 2-5 turns."),
    FISSURE("Fissure", PokemonType.GROUND, 30, 0, 5, MoveCategory.PHYSICAL, "Will OHKO the target."),
    FLAIL("Flail", PokemonType.NORMAL, 100, 0, 15, MoveCategory.PHYSICAL, "Does more damage as HP decreases."),
    FLAME_BURST("Flame Burst", PokemonType.FIRE, 100, 70, 15, MoveCategory.SPECIAL, "Damages Pokemon next to the target as well."),
    FLAME_CHARGE("Flame Charge", PokemonType.FIRE, 100, 50, 20, MoveCategory.PHYSICAL, "Boosts user's Speed by 1 stage."),
    FLAME_WHEEL("Flame Wheel", PokemonType.FIRE, 100, 60, 25, MoveCategory.PHYSICAL, "10% chance to burn. Thaws the user."),
    FLAMETHROWER("Flamethrower", PokemonType.FIRE, 100, 90, 15, MoveCategory.SPECIAL, "10% chance to burn."),
    FLARE_BLITZ("Flare Blitz", PokemonType.FIRE, 100, 120, 15, MoveCategory.PHYSICAL, "Has 1/3 recoil. 10% chance to burn."),
    FLASH("Flash", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers foe's accuracy 1 stage."),
    FLASH_CANNON("Flash Cannon", PokemonType.STEEL, 100, 80, 10, MoveCategory.SPECIAL, "10% chance to lower Special Defense by 1 stage."),
    FLATTER("Flatter", PokemonType.DARK, 100, 0, 15, MoveCategory.NON_DAMAGING, "Confuses the foe. Boosts the foe's Special Attack 1 stage."),
    FLING("Fling", PokemonType.DARK, 100, 0, 10, MoveCategory.PHYSICAL, "Throws the user's hold item at the foe. Power and effect depend on the item."),
    FLOWER_SHIELD("Flower Shield", PokemonType.FAIRY, 0, 0, 10, MoveCategory.NON_DAMAGING, "The user raises the Defense stat of all Grass-type Pokemon in battle."),
    FLY("Fly", PokemonType.FLYING, 95, 90, 15, MoveCategory.PHYSICAL, "User is made invulnerable for one turn, then hits the next turn."),
    FLYING_PRESS("Flying Press", PokemonType.FIGHTING, 95, 80, 10, MoveCategory.PHYSICAL, "Both Fighting-type and Flying-type simultaneously."),
    FOCUS_BLAST("Focus Blast", PokemonType.FIGHTING, 70, 120, 5, MoveCategory.SPECIAL, "10% chance to lower Special Defense by 1 stage."),
    FOCUS_ENERGY("Focus Energy", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Boosts critical hit rate by 1 stage."),
    FOCUS_PUNCH("Focus Punch", PokemonType.FIGHTING, 100, 150, 20, MoveCategory.PHYSICAL, "Fails if the user takes damage before it hits."),
    FOLLOW_ME("Follow Me", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "All moves target the user."),
    FORCE_PALM("Force Palm", PokemonType.FIGHTING, 100, 60, 10, MoveCategory.PHYSICAL, "30% chance to paralyze."),
    FORESIGHT("Foresight", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "Blocks evasion modifiers. Allows Fighting- and Normal-type moves to hit Ghost-types."),
    FORESTS_CURSE("Forest's Curse", PokemonType.GRASS, 100, 0, 20, MoveCategory.NON_DAMAGING, "Adds Grass to the target's type(s). If the target already has three types, the third is replaced."),
    FOUL_PLAY("Foul Play", PokemonType.DARK, 100, 95, 15, MoveCategory.PHYSICAL, "Uses the target's Attack stat in damage calculation."),
    FREEZE_SHOCK("Freeze Shock", PokemonType.ICE, 90, 140, 5, MoveCategory.PHYSICAL, "Hits the turn after being used. 30% chance to paralyze opponent."),
    FREEZE_DRY("Freeze-Dry", PokemonType.ICE, 100, 70, 20, MoveCategory.SPECIAL, "Deals damage to one adjacent target with a 10% chance to freeze it. Super effective against Water-type Pokemon"),
    FRENZY_PLANT("Frenzy Plant", PokemonType.GRASS, 90, 150, 5, MoveCategory.SPECIAL, "User cannot move next turn."),
    FROST_BREATH("Frost Breath", PokemonType.ICE, 90, 60, 10, MoveCategory.SPECIAL, "Always results in a critical hit."),
    FRUSTRATION("Frustration", PokemonType.NORMAL, 100, 0, 20, MoveCategory.PHYSICAL, "No additional effect."),
    FURY_ATTACK("Fury Attack", PokemonType.NORMAL, 85, 15, 20, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    FURY_CUTTER("Fury Cutter", PokemonType.BUG, 95, 40, 20, MoveCategory.PHYSICAL, "Power doubles with each consecutive hit."),
    FURY_SWIPES("Fury Swipes", PokemonType.NORMAL, 80, 18, 15, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    FUSION_BOLT("Fusion Bolt", PokemonType.ELECTRIC, 100, 100, 5, MoveCategory.PHYSICAL, "Power doubles if used after Fusion Flare."),
    FUSION_FLARE("Fusion Flare", PokemonType.FIRE, 100, 100, 5, MoveCategory.SPECIAL, "Power doubles if used after Fusion Bolt."),
    FUTURE_SIGHT("Future Sight", PokemonType.PSYCHIC, 100, 120, 10, MoveCategory.SPECIAL, "Deals damage at the end of the turn after three turns."),
    GASTRO_ACID("Gastro Acid", PokemonType.POISON, 100, 0, 10, MoveCategory.NON_DAMAGING, "Nullifies the foe's ability."),
    GEAR_GRIND("Gear Grind", PokemonType.STEEL, 85, 50, 15, MoveCategory.PHYSICAL, "Hits 2 times in one turn."),
    GEOMANCY("Geomancy", PokemonType.FAIRY, 0, 0, 10, MoveCategory.NON_DAMAGING, "The user charges turn one, then sharply raises Special Attack, Special Defense, and Speed the next turn."),
    GIGA_DRAIN("Giga Drain", PokemonType.GRASS, 100, 75, 10, MoveCategory.SPECIAL, "Leeches 50% damage."),
    GIGA_IMPACT("Giga Impact", PokemonType.NORMAL, 90, 150, 5, MoveCategory.PHYSICAL, "User cannot move next turn."),
    GLACIATE("Glaciate", PokemonType.ICE, 95, 65, 10, MoveCategory.SPECIAL, "Lowers target's Speed by 1 stage."),
    GLARE("Glare", PokemonType.NORMAL, 100, 0, 30, MoveCategory.NON_DAMAGING, "Paralyzes the target."),
    GRASS_KNOT("Grass Knot", PokemonType.GRASS, 100, 0, 20, MoveCategory.SPECIAL, "Deals damage based on the foe's weight."),
    GRASS_PLEDGE("Grass Pledge", PokemonType.GRASS, 100, 80, 10, MoveCategory.SPECIAL, "Use with Grass Pledge and Water Pledge for additional effect."),
    GRASS_WHISTLE("Grass Whistle", PokemonType.GRASS, 55, 0, 15, MoveCategory.NON_DAMAGING, "Puts the foe to sleep."),
    GRASSY_TERRAIN("Grassy Terrain", PokemonType.GRASS, 0, 0, 10, MoveCategory.NON_DAMAGING, "For five turns, Pokemon on the ground restore 1/16 of their HP each turn. Their Grass-type moves are powered up by 50%."),
    GRAVITY("Gravity", PokemonType.PSYCHIC, 0, 0, 5, MoveCategory.NON_DAMAGING, "For 5 turns, prevents flying or jumping; also disables Ground immunities."),
    GROWL("Growl", PokemonType.NORMAL, 100, 0, 40, MoveCategory.NON_DAMAGING, "Lowers target's Attack by 1 stage."),
    GROWTH("Growth", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "Boosts Attack and Special Attack by one stage. Boosts Attack and Special Attack by two stages in bright sunlight."),
    GRUDGE("Grudge", PokemonType.GHOST, 0, 0, 5, MoveCategory.NON_DAMAGING, "If the user faints, the foe's attack loses all of its PP."),
    GUARD_SPLIT("Guard Split", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Averages Defense and Special Defense stats of the user with the target."),
    GUARD_SWAP("Guard Swap", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Swaps Defense and Special Defense boosts and drops."),
    GUILLOTINE("Guillotine", PokemonType.NORMAL, 30, 0, 5, MoveCategory.PHYSICAL, "Will OHKO the target."),
    GUNK_SHOT("Gunk Shot", PokemonType.POISON, 80, 120, 5, MoveCategory.PHYSICAL, "30% chance to poison."),
    GUST("Gust", PokemonType.FLYING, 100, 40, 35, MoveCategory.SPECIAL, "Hits Pokemon using Fly for twice Base Power."),
    GYRO_BALL("Gyro Ball", PokemonType.STEEL, 100, 0, 5, MoveCategory.PHYSICAL, "Does damage based on the foe's Speed and the user's Speed."),
    HAIL("Hail", PokemonType.ICE, 0, 0, 10, MoveCategory.NON_DAMAGING, "Summons hail for 5 turns."),
    HAMMER_ARM("Hammer Arm", PokemonType.FIGHTING, 90, 100, 10, MoveCategory.PHYSICAL, "Lowers user's Speed by 1 stage."),
    HAPPY_HOUR("Happy Hour", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "No competitive effect. (Doubles the prize money received after battle.)"),
    HARDEN("Harden", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Boosts user's Defense by one stage."),
    HAZE("Haze", PokemonType.ICE, 0, 0, 30, MoveCategory.NON_DAMAGING, "Eliminates all stat changes."),
    HEAD_CHARGE("Head Charge", PokemonType.NORMAL, 100, 120, 15, MoveCategory.PHYSICAL, "Has 25% recoil."),
    HEAD_SMASH("Head Smash", PokemonType.ROCK, 80, 150, 5, MoveCategory.PHYSICAL, "Has 1/2 recoil."),
    HEADBUTT("Headbutt", PokemonType.NORMAL, 100, 70, 15, MoveCategory.PHYSICAL, "30% chance to flinch the target."),
    HEAL_BELL("Heal Bell", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "Cures status on the user's team."),
    HEAL_BLOCK("Heal Block", PokemonType.PSYCHIC, 100, 0, 15, MoveCategory.NON_DAMAGING, "Prevents the foes from using healing moves for 5 turns."),
    HEAL_ORDER("Heal Order", PokemonType.BUG, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% max HP."),
    HEAL_PULSE("Heal Pulse", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals the target by 50% its max HP."),
    HEALING_WISH("Healing Wish", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "KOs the user and heals the next Pokemon in."),
    HEART_STAMP("Heart Stamp", PokemonType.PSYCHIC, 100, 60, 25, MoveCategory.PHYSICAL, "30% chance to flinch the target."),
    HEART_SWAP("Heart Swap", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Swaps stat boosts and drops."),
    HEAT_CRASH("Heat Crash", PokemonType.FIRE, 100, 0, 10, MoveCategory.PHYSICAL, "Deals damage based on both the user's and the target's weight."),
    HEAT_WAVE("Heat Wave", PokemonType.FIRE, 90, 95, 10, MoveCategory.SPECIAL, "10% chance to burn."),
    HEAVY_SLAM("Heavy Slam", PokemonType.STEEL, 100, 0, 10, MoveCategory.PHYSICAL, "Deals damage based on both the user's and the target's weight."),
    HELPING_HAND("Helping Hand", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Increases power of ally's moves by 50%."),
    HEX("Hex", PokemonType.GHOST, 100, 65, 10, MoveCategory.SPECIAL, "Base Power doubles if target has a status ailment."),
    HIDDEN_POWER_BUG("Hidden Power Bug", PokemonType.BUG, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_DARK("Hidden Power Dark", PokemonType.DARK, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_DRAGON("Hidden Power Dragon", PokemonType.DRAGON, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_ELECTRIC("Hidden Power Electric", PokemonType.ELECTRIC, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_FIGHTING("Hidden Power Fighting", PokemonType.FIGHTING, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_FIRE("Hidden Power Fire", PokemonType.FIRE, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_FLYING("Hidden Power Flying", PokemonType.FLYING, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_GHOST("Hidden Power Ghost", PokemonType.GHOST, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_GRASS("Hidden Power Grass", PokemonType.GRASS, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_GROUND("Hidden Power Ground", PokemonType.GROUND, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_ICE("Hidden Power Ice", PokemonType.ICE, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_POISON("Hidden Power Poison", PokemonType.POISON, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_PSYCHIC("Hidden Power Psychic", PokemonType.PSYCHIC, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_ROCK("Hidden Power Rock", PokemonType.ROCK, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_STEEL("Hidden Power Steel", PokemonType.STEEL, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIDDEN_POWER_WATER("Hidden Power Water", PokemonType.WATER, 100, 60, 15, MoveCategory.SPECIAL, "Type is based on the user's IVs."),
    HIGH_JUMP_KICK("High Jump Kick", PokemonType.FIGHTING, 90, 130, 10, MoveCategory.PHYSICAL, "If it misses, user loses HP equal to 1/2 the damage that would have been dealt."),
    HOLD_BACK("Hold Back", PokemonType.NORMAL, 100, 40, 40, MoveCategory.PHYSICAL, "Deals damage to one adjacent target but leaves it with at least 1HP. Makes contact."),
    HOLD_HANDS("Hold Hands", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "No in-game effect."),
    HONE_CLAWS("Hone Claws", PokemonType.DARK, 0, 0, 15, MoveCategory.NON_DAMAGING, "Boosts Attack and accuracy one stage."),
    HORN_ATTACK("Horn Attack", PokemonType.NORMAL, 100, 65, 25, MoveCategory.PHYSICAL, "No additional effect."),
    HORN_DRILL("Horn Drill", PokemonType.NORMAL, 30, 0, 5, MoveCategory.PHYSICAL, "Will OHKO the target."),
    HORN_LEECH("Horn Leech", PokemonType.GRASS, 100, 75, 10, MoveCategory.PHYSICAL, "Leeches 50% of the damage dealt."),
    HOWL("Howl", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "Boosts Attack by 1 stage."),
    HURRICANE("Hurricane", PokemonType.FLYING, 70, 110, 10, MoveCategory.SPECIAL, "30% chance to confuse the target."),
    HYDRO_CANNON("Hydro Cannon", PokemonType.WATER, 90, 150, 5, MoveCategory.SPECIAL, "User cannot move next turn."),
    HYDRO_PUMP("Hydro Pump", PokemonType.WATER, 80, 110, 5, MoveCategory.SPECIAL, "No additional effect."),
    HYPER_BEAM("Hyper Beam", PokemonType.NORMAL, 90, 150, 5, MoveCategory.SPECIAL, "User cannot move next turn."),
    HYPER_FANG("Hyper Fang", PokemonType.NORMAL, 90, 80, 15, MoveCategory.PHYSICAL, "10% chance to flinch the target."),
    HYPER_VOICE("Hyper Voice", PokemonType.NORMAL, 100, 90, 10, MoveCategory.SPECIAL, "No additional effect."),
    HYPERSPACE_HOLE("Hyperspace Hole", PokemonType.PSYCHIC, 0, 80, 5, MoveCategory.SPECIAL, "Ignores the effects of Protect and Detect."),
    HYPNOSIS("Hypnosis", PokemonType.PSYCHIC, 60, 0, 20, MoveCategory.NON_DAMAGING, "Puts the foe to sleep."),
    ICE_BALL("Ice Ball", PokemonType.ICE, 90, 30, 20, MoveCategory.PHYSICAL, "Doubles in power with each hit. Repeats for 5 turns."),
    ICE_BEAM("Ice Beam", PokemonType.ICE, 100, 90, 10, MoveCategory.SPECIAL, "10% chance to freeze the target."),
    ICE_BURN("Ice Burn", PokemonType.ICE, 90, 140, 5, MoveCategory.SPECIAL, "Hits the turn after being used. 30% chance to burn the target."),
    ICE_FANG("Ice Fang", PokemonType.ICE, 95, 65, 15, MoveCategory.PHYSICAL, "10% chance to flinch. 10% chance to freeze."),
    ICE_PUNCH("Ice Punch", PokemonType.ICE, 100, 75, 15, MoveCategory.PHYSICAL, "10% chance to freeze the target."),
    ICE_SHARD("Ice Shard", PokemonType.ICE, 100, 40, 30, MoveCategory.PHYSICAL, "The user always attacks first."),
    ICICLE_CRASH("Icicle Crash", PokemonType.ICE, 90, 85, 10, MoveCategory.PHYSICAL, "30% chance to flinch the target."),
    ICICLE_SPEAR("Icicle Spear", PokemonType.ICE, 100, 25, 30, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    ICY_WIND("Icy Wind", PokemonType.ICE, 95, 55, 15, MoveCategory.SPECIAL, "Lowers foe's Speed by 1 stage."),
    IMPRISON("Imprison", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "No foe can use any of the user's moves."),
    INCINERATE("Incinerate", PokemonType.FIRE, 100, 60, 15, MoveCategory.SPECIAL, "Removes the target's Berry."),
    INFERNO("Inferno", PokemonType.FIRE, 50, 100, 5, MoveCategory.SPECIAL, "Burns the target."),
    INFESTATION("Infestation", PokemonType.BUG, 100, 20, 20, MoveCategory.SPECIAL, "Traps and damages target for 4-5 turns."),
    INGRAIN("Ingrain", PokemonType.GRASS, 0, 0, 20, MoveCategory.NON_DAMAGING, "Heals the user 1/16 its max HP each turn. Prevents the user from switching."),
    ION_DELUGE("Ion Deluge", PokemonType.ELECTRIC, 0, 0, 25, MoveCategory.NON_DAMAGING, "Changes Normal-type moves to Electric-type moves."),
    IRON_DEFENSE("Iron Defense", PokemonType.STEEL, 0, 0, 15, MoveCategory.NON_DAMAGING, "Boosts Defense by 2 stages."),
    IRON_HEAD("Iron Head", PokemonType.STEEL, 100, 80, 15, MoveCategory.PHYSICAL, "30% chance to flinch."),
    IRON_TAIL("Iron Tail", PokemonType.STEEL, 75, 100, 15, MoveCategory.PHYSICAL, "30% chance to lower Defense by 1 stage."),
    JUDGMENT("Judgment", PokemonType.NORMAL, 100, 100, 10, MoveCategory.SPECIAL, "Type is dependent on the user's held plate item."),
    JUMP_KICK("Jump Kick", PokemonType.FIGHTING, 95, 100, 10, MoveCategory.PHYSICAL, "If it misses, user loses HP equal to 1/2 the damage that would have been dealt."),
    KARATE_CHOP("Karate Chop", PokemonType.FIGHTING, 100, 50, 25, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    KINESIS("Kinesis", PokemonType.PSYCHIC, 80, 0, 15, MoveCategory.NON_DAMAGING, "Lowers target's accuracy by 1 stage."),
    KINGS_SHIELD("King's Shield", PokemonType.STEEL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Protects the user from attacks. Contactors get their Attack lowered by 2 stages. Priority +4"),
    KNOCK_OFF("Knock Off", PokemonType.DARK, 100, 65, 20, MoveCategory.PHYSICAL, "Power is boosted 1.5x if user is holding a removable item. Removes the target's item."),
    LANDS_WRATH("Land's Wrath", PokemonType.GROUND, 100, 90, 10, MoveCategory.PHYSICAL, "Deals damage to one adjacent target."),
    LAST_RESORT("Last Resort", PokemonType.NORMAL, 100, 140, 5, MoveCategory.PHYSICAL, "Can only be used if all other moves have been used once."),
    LAVA_PLUME("Lava Plume", PokemonType.FIRE, 100, 80, 15, MoveCategory.SPECIAL, "30% chance to burn."),
    LEAF_BLADE("Leaf Blade", PokemonType.GRASS, 100, 90, 15, MoveCategory.PHYSICAL, "High critical hit rate."),
    LEAF_STORM("Leaf Storm", PokemonType.GRASS, 90, 130, 5, MoveCategory.SPECIAL, "Lowers user's Special Attack by 2 stages."),
    LEAF_TORNADO("Leaf Tornado", PokemonType.GRASS, 90, 65, 10, MoveCategory.SPECIAL, "50% chance to lower target's accuracy by 1 stage."),
    LEECH_LIFE("Leech Life", PokemonType.BUG, 100, 20, 15, MoveCategory.PHYSICAL, "Leeches 50% of the damage dealt."),
    LEECH_SEED("Leech Seed", PokemonType.GRASS, 90, 0, 10, MoveCategory.NON_DAMAGING, "Leeches 1/8 of the target's HP each turn."),
    LEER("Leer", PokemonType.NORMAL, 100, 0, 30, MoveCategory.NON_DAMAGING, "Lowers target's Defense by 1 stage."),
    LICK("Lick", PokemonType.GHOST, 100, 30, 30, MoveCategory.PHYSICAL, "30% chance to paralyze the target."),
    LIGHT_SCREEN("Light Screen", PokemonType.PSYCHIC, 0, 0, 30, MoveCategory.NON_DAMAGING, "Lowers damage from special attacks for 5 turns."),
    LIGHT_OF_RUIN("Light of Ruin", PokemonType.FAIRY, 90, 140, 5, MoveCategory.SPECIAL, "Has 1/2 recoil."),
    LOCK_ON("Lock-On", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "The next move used will always hit."),
    LOVELY_KISS("Lovely Kiss", PokemonType.NORMAL, 75, 0, 10, MoveCategory.NON_DAMAGING, "Puts the target to sleep."),
    LOW_KICK("Low Kick", PokemonType.FIGHTING, 100, 0, 20, MoveCategory.PHYSICAL, "Deals damage based on the foe's weight."),
    LOW_SWEEP("Low Sweep", PokemonType.FIGHTING, 100, 65, 20, MoveCategory.PHYSICAL, "Lowers target's Speed by 1 stage."),
    LUCKY_CHANT("Lucky Chant", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Blocks critical hits for 5 turns."),
    LUNAR_DANCE("Lunar Dance", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "KOs the user, then heals the next Pokemon in."),
    LUSTER_PURGE("Luster Purge", PokemonType.PSYCHIC, 100, 70, 5, MoveCategory.SPECIAL, "50% chance to lower Special Defense by 1 stage."),
    MACH_PUNCH("Mach Punch", PokemonType.FIGHTING, 100, 40, 30, MoveCategory.PHYSICAL, "The user always attacks first."),
    MAGIC_COAT("Magic Coat", PokemonType.PSYCHIC, 0, 0, 15, MoveCategory.NON_DAMAGING, "Bounces back certain non-damaging moves."),
    MAGIC_ROOM("Magic Room", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Held items have no effect for 5 turns."),
    MAGICAL_LEAF("Magical Leaf", PokemonType.GRASS, 0, 60, 20, MoveCategory.SPECIAL, "Ignores accuracy modifiers."),
    MAGMA_STORM("Magma Storm", PokemonType.FIRE, 75, 100, 5, MoveCategory.SPECIAL, "Traps and damages over multiple turns."),
    MAGNET_BOMB("Magnet Bomb", PokemonType.STEEL, 0, 60, 20, MoveCategory.PHYSICAL, "Ignores accuracy modifiers."),
    MAGNET_RISE("Magnet Rise", PokemonType.ELECTRIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "User becomes immune to Ground moves for 5 turns."),
    MAGNETIC_FLUX("Magnetic Flux", PokemonType.ELECTRIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Raises the Defense and Special Defense stats of ally Pokemon with the Plus or Minus Ability."),
    MAGNITUDE("Magnitude", PokemonType.GROUND, 100, 0, 30, MoveCategory.PHYSICAL, "Has variable damage."),
    MAT_BLOCK("Mat Block", PokemonType.FIGHTING, 0, 0, 10, MoveCategory.NON_DAMAGING, "The user protects itself and its allies from damaging moves. Only works first turn out."),
    ME_FIRST("Me First", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Uses the foe's attack at 1.5x power. Must be faster to work."),
    MEAN_LOOK("Mean Look", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "The target cannot switch out."),
    MEDITATE("Meditate", PokemonType.PSYCHIC, 0, 0, 40, MoveCategory.NON_DAMAGING, "Boosts user's Attack by 1 stage."),
    MEGA_DRAIN("Mega Drain", PokemonType.GRASS, 100, 40, 15, MoveCategory.SPECIAL, "Leeches 50% of the damage dealt."),
    MEGA_KICK("Mega Kick", PokemonType.NORMAL, 75, 120, 5, MoveCategory.PHYSICAL, "No additional effect."),
    MEGA_PUNCH("Mega Punch", PokemonType.NORMAL, 85, 80, 20, MoveCategory.PHYSICAL, "No additional effect."),
    MEGAHORN("Megahorn", PokemonType.BUG, 85, 120, 10, MoveCategory.PHYSICAL, "No additional effect."),
    MEMENTO("Memento", PokemonType.DARK, 100, 0, 10, MoveCategory.NON_DAMAGING, "User faints. Lowers foe's Attack and Special Attack by 2 stages."),
    METAL_BURST("Metal Burst", PokemonType.STEEL, 100, 0, 10, MoveCategory.PHYSICAL, "Counters foe's attack with 1.5x damage, but must go last."),
    METAL_CLAW("Metal Claw", PokemonType.STEEL, 95, 50, 35, MoveCategory.PHYSICAL, "10% chance to boost Attack by 1 stage."),
    METAL_SOUND("Metal Sound", PokemonType.STEEL, 85, 0, 40, MoveCategory.NON_DAMAGING, "Lower's Special Defense by 2 stages."),
    METEOR_MASH("Meteor Mash", PokemonType.STEEL, 90, 90, 10, MoveCategory.PHYSICAL, "20% chance to raise Attack by 1 stage."),
    METRONOME("Metronome", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Picks a random move."),
    MILK_DRINK("Milk Drink", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% of max HP."),
    MIMIC("Mimic", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Copies the last move used by the target."),
    MIND_READER("Mind Reader", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "The next move used will always hit."),
    MINIMIZE("Minimize", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Boosts evasion by 2 stages."),
    MIRACLE_EYE("Miracle Eye", PokemonType.PSYCHIC, 0, 0, 40, MoveCategory.NON_DAMAGING, "Nullifies evasion. Allows Psychic-type moves to hit Darks."),
    MIRROR_COAT("Mirror Coat", PokemonType.PSYCHIC, 100, 0, 20, MoveCategory.SPECIAL, "If hit by a special attack, returns double the damage."),
    MIRROR_MOVE("Mirror Move", PokemonType.FLYING, 0, 0, 20, MoveCategory.NON_DAMAGING, "Uses the last move that hit the user."),
    MIRROR_SHOT("Mirror Shot", PokemonType.STEEL, 85, 65, 10, MoveCategory.SPECIAL, "30% chance to lower accuracy by 1 stage."),
    MIST("Mist", PokemonType.ICE, 0, 0, 30, MoveCategory.NON_DAMAGING, "Prevents moves that lower stats from working for 5 turns."),
    MIST_BALL("Mist Ball", PokemonType.PSYCHIC, 100, 70, 5, MoveCategory.SPECIAL, "50% chance to lower Special Attack by 1 stage."),
    MISTY_TERRAIN("Misty Terrain", PokemonType.FAIRY, 0, 0, 10, MoveCategory.NON_DAMAGING, "For five turns, Grounded Pokemon cannot have major status problems or confusion inflicted on them by other Pokemon. Their Dragon-type moves are weakened by 50%."),
    MOONBLAST("Moonblast", PokemonType.FAIRY, 100, 95, 15, MoveCategory.SPECIAL, "Deals damage to one adjacent target with a 30% chance to lower its Special Attack by 1 stage."),
    MOONLIGHT("Moonlight", PokemonType.FAIRY, 0, 0, 5, MoveCategory.NON_DAMAGING, "Heals variably depending on the weather."),
    MORNING_SUN("Morning Sun", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "Heals variably depending on the weather."),
    MUD_BOMB("Mud Bomb", PokemonType.GROUND, 85, 65, 10, MoveCategory.SPECIAL, "30% chance to lower accuracy by 1 stage."),
    MUD_SHOT("Mud Shot", PokemonType.GROUND, 95, 55, 15, MoveCategory.SPECIAL, "Lowers Speed by 1 stage."),
    MUD_SPORT("Mud Sport", PokemonType.GROUND, 0, 0, 15, MoveCategory.NON_DAMAGING, "Electric-type attacks do 50% damage."),
    MUD_SLAP("Mud-Slap", PokemonType.GROUND, 100, 20, 10, MoveCategory.SPECIAL, "Lowers accuracy by 1 stage."),
    MUDDY_WATER("Muddy Water", PokemonType.WATER, 85, 90, 10, MoveCategory.SPECIAL, "30% chance to lower accuracy by 1 stage."),
    MYSTICAL_FIRE("Mystical Fire", PokemonType.FIRE, 100, 65, 10, MoveCategory.SPECIAL, "Deals damage to one adjacent target and lowers its Special Attack by 1 stage."),
    NASTY_PLOT("Nasty Plot", PokemonType.DARK, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Special Attack by 2 stages."),
    NATURAL_GIFT("Natural Gift", PokemonType.NORMAL, 100, 0, 15, MoveCategory.PHYSICAL, "Power and type depends on the user's held Berry."),
    NATURE_POWER("Nature Power", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Attack changes based on terrain."),
    NEEDLE_ARM("Needle Arm", PokemonType.GRASS, 100, 60, 15, MoveCategory.PHYSICAL, "30% chance to flinch."),
    NIGHT_DAZE("Night Daze", PokemonType.DARK, 95, 85, 10, MoveCategory.SPECIAL, "40% chance to lower target's accuracy by 1 stage."),
    NIGHT_SHADE("Night Shade", PokemonType.GHOST, 100, 0, 15, MoveCategory.SPECIAL, "Does damage equal to the user's level."),
    NIGHT_SLASH("Night Slash", PokemonType.DARK, 100, 70, 15, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    NIGHTMARE("Nightmare", PokemonType.GHOST, 100, 0, 15, MoveCategory.NON_DAMAGING, "Does 1/4 of the target's max HP per turn to a sleeping target."),
    NOBLE_ROAR("Noble Roar", PokemonType.NORMAL, 100, 0, 30, MoveCategory.NON_DAMAGING, "Lowers the target's Attack and Special Attack by 1 stage. Pokemon protected by Magic Coat or the Ability Magic Bounce are unaffected and instead use this move themselves."),
    NUZZLE("Nuzzle", PokemonType.ELECTRIC, 100, 20, 20, MoveCategory.PHYSICAL, "Deals damage and paralyzes the target."),
    OBLIVION_WING("Oblivion Wing", PokemonType.FLYING, 100, 80, 10, MoveCategory.SPECIAL, "Deals damage to one adjacent target. The user recovers 75% of the HP lost by the target, rounded up."),
    OCTAZOOKA("Octazooka", PokemonType.WATER, 85, 65, 10, MoveCategory.SPECIAL, "50% chance to lower accuracy by 1 stage."),
    ODOR_SLEUTH("Odor Sleuth", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "Blocks evasion modifiers. Allows Fighting- and Normal-type moves to hit Ghosts."),
    OMINOUS_WIND("Ominous Wind", PokemonType.GHOST, 100, 60, 5, MoveCategory.SPECIAL, "10% chance to boost all stats by 1 stage."),
    OUTRAGE("Outrage", PokemonType.DRAGON, 100, 120, 15, MoveCategory.PHYSICAL, "Repeats for 2-3 turns. Confuses at the end."),
    OVERHEAT("Overheat", PokemonType.FIRE, 90, 130, 5, MoveCategory.SPECIAL, "Lowers Special Attack by 2 stages."),
    PAIN_SPLIT("Pain Split", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Averages both Pokemon's HP."),
    PARABOLIC_CHARGE("Parabolic Charge", PokemonType.ELECTRIC, 100, 50, 20, MoveCategory.SPECIAL, "Deals damage to all adjacent targets. The user recovers half of the HP lost by the target, rounded up."),
    PARTING_SHOT("Parting Shot", PokemonType.DARK, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers all adjacent foes' Attack and Special Attack by 1 stage, then the user switches out."),
    PAY_DAY("Pay Day", PokemonType.NORMAL, 100, 40, 20, MoveCategory.PHYSICAL, "No additional effect."),
    PAYBACK("Payback", PokemonType.DARK, 100, 50, 10, MoveCategory.PHYSICAL, "Base Power doubles if the foe has taken its turn."),
    PECK("Peck", PokemonType.FLYING, 100, 35, 35, MoveCategory.PHYSICAL, "No additional effect."),
    PERISH_SONG("Perish Song", PokemonType.NORMAL, 0, 0, 5, MoveCategory.NON_DAMAGING, "All active Pokemon faint after 3 turns."),
    PETAL_BLIZZARD("Petal Blizzard", PokemonType.GRASS, 100, 90, 15, MoveCategory.PHYSICAL, "Hits all adjacent Pokemon."),
    PETAL_DANCE("Petal Dance", PokemonType.GRASS, 100, 120, 10, MoveCategory.SPECIAL, "Repeats for 2-3 turns. Confuses the user at the end."),
    PHANTOM_FORCE("Phantom Force", PokemonType.GHOST, 100, 90, 10, MoveCategory.PHYSICAL, "Deals damage to one adjacent target and breaks through Protect and Detect for this turn, allowing other Pokemon to attack the target normally. This attack charges on the first turn and strikes on the second. On the first turn, the user avoids all attacks. The user cannot make a move between turns. If the user is holding a Power Herb, the move completes in one turn. Makes contact."),
    PIN_MISSILE("Pin Missile", PokemonType.BUG, 95, 25, 20, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    PLAY_NICE("Play Nice", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Lowers the target's Attack by 1 stage. Ignores Protect."),
    PLAY_ROUGH("Play Rough", PokemonType.FAIRY, 90, 90, 10, MoveCategory.PHYSICAL, "May lower the target's Attack stat by 1."),
    PLUCK("Pluck", PokemonType.FLYING, 100, 60, 20, MoveCategory.PHYSICAL, "Uses foe's Berry."),
    POISON_FANG("Poison Fang", PokemonType.POISON, 100, 50, 15, MoveCategory.PHYSICAL, "30% chance to inflict bad poison."),
    POISON_GAS("Poison Gas", PokemonType.POISON, 90, 0, 40, MoveCategory.NON_DAMAGING, "Poisons the target."),
    POISON_JAB("Poison Jab", PokemonType.POISON, 100, 80, 20, MoveCategory.PHYSICAL, "30% chance to poison."),
    POISON_POWDER("Poison Powder", PokemonType.POISON, 75, 0, 35, MoveCategory.NON_DAMAGING, "Poisons the target."),
    POISON_STING("Poison Sting", PokemonType.POISON, 100, 15, 35, MoveCategory.PHYSICAL, "30% chance to poison."),
    POISON_TAIL("Poison Tail", PokemonType.POISON, 100, 50, 25, MoveCategory.PHYSICAL, "Has a high critical hit rate. 10% chance to poison."),
    POUND("Pound", PokemonType.NORMAL, 100, 40, 35, MoveCategory.PHYSICAL, "No additional effect."),
    POWDER("Powder", PokemonType.BUG, 100, 0, 20, MoveCategory.NON_DAMAGING, "Covers the target in powder that explodes if the target uses a Fire-type move. +1 Priority."),
    POWDER_SNOW("Powder Snow", PokemonType.ICE, 100, 40, 25, MoveCategory.SPECIAL, "10% chance to freeze."),
    POWER_GEM("Power Gem", PokemonType.ROCK, 100, 80, 20, MoveCategory.SPECIAL, "No additional effect."),
    POWER_SPLIT("Power Split", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Averages Attack and Special Attack with the target."),
    POWER_SWAP("Power Swap", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Swaps Attack and Special Attack boosts and drops with the foe."),
    POWER_TRICK("Power Trick", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Swaps user's Attack and Defense stats."),
    POWER_WHIP("Power Whip", PokemonType.GRASS, 85, 120, 10, MoveCategory.PHYSICAL, "No additional effect."),
    POWER_UP_PUNCH("Power-Up Punch", PokemonType.FIGHTING, 100, 40, 20, MoveCategory.PHYSICAL, "Hitting a target raises the Attack stat."),
    PRESENT("Present", PokemonType.NORMAL, 90, 0, 15, MoveCategory.PHYSICAL, "Has random power and a chance to heal the target."),
    PROTECT("Protect", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Prevents anything from working on the user that turn."),
    PSYBEAM("Psybeam", PokemonType.PSYCHIC, 100, 65, 20, MoveCategory.SPECIAL, "10% chance to confuse."),
    PSYCH_UP("Psych Up", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Copies the foe's stat changes."),
    PSYCHIC("Psychic", PokemonType.PSYCHIC, 100, 90, 10, MoveCategory.SPECIAL, "10% chance to lower Special Defense 1 stage."),
    PSYCHO_BOOST("Psycho Boost", PokemonType.PSYCHIC, 90, 140, 5, MoveCategory.SPECIAL, "Lowers user's Special Attack by 2 stages."),
    PSYCHO_CUT("Psycho Cut", PokemonType.PSYCHIC, 100, 70, 20, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    PSYCHO_SHIFT("Psycho Shift", PokemonType.PSYCHIC, 100, 0, 10, MoveCategory.NON_DAMAGING, "Shifts the user's status effect to the foe."),
    PSYSHOCK("Psyshock", PokemonType.PSYCHIC, 100, 80, 10, MoveCategory.SPECIAL, "Damage is based on the target's Defense stat."),
    PSYSTRIKE("Psystrike", PokemonType.PSYCHIC, 100, 100, 10, MoveCategory.SPECIAL, "Damage is based on the target's Defense stat."),
    PSYWAVE("Psywave", PokemonType.PSYCHIC, 80, 0, 15, MoveCategory.SPECIAL, "Does random damage equal to .5x-1.5x the user's level."),
    PUNISHMENT("Punishment", PokemonType.DARK, 100, 0, 5, MoveCategory.PHYSICAL, "Does more damage to foes with stat boosts."),
    PURSUIT("Pursuit", PokemonType.DARK, 100, 40, 20, MoveCategory.PHYSICAL, "Doubles in power if the target switches, and hits them before they can escape."),
    QUASH("Quash", PokemonType.DARK, 100, 0, 15, MoveCategory.NON_DAMAGING, "Forces the target to move last."),
    QUICK_ATTACK("Quick Attack", PokemonType.NORMAL, 100, 40, 30, MoveCategory.PHYSICAL, "The user always attacks first."),
    QUICK_GUARD("Quick Guard", PokemonType.FIGHTING, 0, 0, 15, MoveCategory.NON_DAMAGING, "Protects user and allies from priority attacks."),
    QUIVER_DANCE("Quiver Dance", PokemonType.BUG, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts the user's Special Attack, Special Defense, and Speed by 1 stage."),
    RAGE("Rage", PokemonType.NORMAL, 100, 20, 20, MoveCategory.PHYSICAL, "Boosts Atk 1 stage if hit."),
    RAGE_POWDER("Rage Powder", PokemonType.BUG, 0, 0, 20, MoveCategory.NON_DAMAGING, "All moves target the user."),
    RAIN_DANCE("Rain Dance", PokemonType.WATER, 0, 0, 5, MoveCategory.NON_DAMAGING, "Summons rain for 5 turns."),
    RAPID_SPIN("Rapid Spin", PokemonType.NORMAL, 100, 20, 40, MoveCategory.PHYSICAL, "Removes Leech Seed and Spikes."),
    RAZOR_LEAF("Razor Leaf", PokemonType.GRASS, 95, 55, 25, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    RAZOR_SHELL("Razor Shell", PokemonType.WATER, 95, 75, 10, MoveCategory.PHYSICAL, "50% chance to lower target's Defense by 1 stage."),
    RAZOR_WIND("Razor Wind", PokemonType.NORMAL, 100, 80, 10, MoveCategory.SPECIAL, "Charges up the first turn; attacks on the second turn. Has a high critical hit rate."),
    RECOVER("Recover", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% of user's max HP."),
    RECYCLE("Recycle", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Restores a used up item."),
    REFLECT("Reflect", PokemonType.PSYCHIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Lowers damage from physical attacks for 5 turns."),
    REFLECT_TYPE("Reflect Type", PokemonType.NORMAL, 0, 0, 15, MoveCategory.NON_DAMAGING, "User becomes the same type as the target."),
    REFRESH("Refresh", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Removes status."),
    RELIC_SONG("Relic Song", PokemonType.NORMAL, 100, 75, 10, MoveCategory.SPECIAL, "10% chance to put target to sleep. If used by Meloetta, causes it to change from Aria Forme to Pirouette Forme."),
    REST("Rest", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "The user goes to sleep for two turns and restores all HP."),
    RETALIATE("Retaliate", PokemonType.NORMAL, 100, 70, 5, MoveCategory.PHYSICAL, "Power doubles if the user's teammate fainted the previous turn."),
    RETURN("Return", PokemonType.NORMAL, 100, 0, 20, MoveCategory.PHYSICAL, "No additional effect."),
    REVENGE("Revenge", PokemonType.FIGHTING, 100, 60, 10, MoveCategory.PHYSICAL, "Doubles in power if damaged."),
    REVERSAL("Reversal", PokemonType.FIGHTING, 100, 0, 15, MoveCategory.PHYSICAL, "Does more damage as HP decreases."),
    ROAR("Roar", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Forces a switch to a random Pokemon."),
    ROAR_OF_TIME("Roar of Time", PokemonType.DRAGON, 90, 150, 5, MoveCategory.SPECIAL, "User cannot move next turn."),
    ROCK_BLAST("Rock Blast", PokemonType.ROCK, 90, 25, 10, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    ROCK_CLIMB("Rock Climb", PokemonType.NORMAL, 85, 90, 20, MoveCategory.PHYSICAL, "20% chance to confuse."),
    ROCK_POLISH("Rock Polish", PokemonType.ROCK, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Speed by 2 stages."),
    ROCK_SLIDE("Rock Slide", PokemonType.ROCK, 90, 75, 10, MoveCategory.PHYSICAL, "30% chance to flinch."),
    ROCK_SMASH("Rock Smash", PokemonType.FIGHTING, 100, 40, 15, MoveCategory.PHYSICAL, "50% chance to lower Defense by 1 stage."),
    ROCK_THROW("Rock Throw", PokemonType.ROCK, 90, 50, 15, MoveCategory.PHYSICAL, "No additional effect."),
    ROCK_TOMB("Rock Tomb", PokemonType.ROCK, 95, 60, 10, MoveCategory.PHYSICAL, "Lowers Speed by 1 stage."),
    ROCK_WRECKER("Rock Wrecker", PokemonType.ROCK, 90, 150, 5, MoveCategory.PHYSICAL, "User cannot move next turn."),
    ROLE_PLAY("Role Play", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Copies the foe's ability and overwrites the user's ability."),
    ROLLING_KICK("Rolling Kick", PokemonType.FIGHTING, 85, 60, 15, MoveCategory.PHYSICAL, "30% chance to flinch."),
    ROLLOUT("Rollout", PokemonType.ROCK, 90, 30, 20, MoveCategory.PHYSICAL, "Doubles in power with each hit. Repeats for 5 turns."),
    ROOST("Roost", PokemonType.FLYING, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% HP. Temporarily removes the user's Flying-type."),
    ROTOTILLER("Rototiller", PokemonType.GROUND, 0, 0, 10, MoveCategory.NON_DAMAGING, "Raises the Attack and Special Attack stats of Grass-type Pokemon."),
    ROUND("Round", PokemonType.NORMAL, 100, 60, 15, MoveCategory.SPECIAL, "Power doubles if a teammate uses Round in the same turn."),
    SACRED_FIRE("Sacred Fire", PokemonType.FIRE, 95, 100, 5, MoveCategory.PHYSICAL, "50% chance to burn. Thaws the user."),
    SACRED_SWORD("Sacred Sword", PokemonType.FIGHTING, 100, 90, 15, MoveCategory.PHYSICAL, "Ignores the target's stat changes."),
    SAFEGUARD("Safeguard", PokemonType.NORMAL, 0, 0, 25, MoveCategory.NON_DAMAGING, "Blocks status conditions for 5 turns."),
    SAND_ATTACK("Sand Attack", PokemonType.GROUND, 100, 0, 15, MoveCategory.NON_DAMAGING, "Lowers foe's accuracy by 1 stage."),
    SAND_TOMB("Sand Tomb", PokemonType.GROUND, 85, 35, 15, MoveCategory.PHYSICAL, "Traps and damages target for 4-5 turns."),
    SANDSTORM("Sandstorm", PokemonType.ROCK, 0, 0, 10, MoveCategory.NON_DAMAGING, "Summons a sandstorm for 5 turns."),
    SCALD("Scald", PokemonType.WATER, 100, 80, 15, MoveCategory.SPECIAL, "30% chance to burn the target. Thaws the user."),
    SCARY_FACE("Scary Face", PokemonType.NORMAL, 90, 0, 10, MoveCategory.NON_DAMAGING, "Lowers Speed by 2 stages."),
    SCRATCH("Scratch", PokemonType.NORMAL, 100, 40, 35, MoveCategory.PHYSICAL, "No additional effect."),
    SCREECH("Screech", PokemonType.NORMAL, 85, 0, 40, MoveCategory.NON_DAMAGING, "Lowers foe's Defense by 2 stages."),
    SEARING_SHOT("Searing Shot", PokemonType.FIRE, 100, 100, 5, MoveCategory.SPECIAL, "30% chance to burn the target."),
    SECRET_POWER("Secret Power", PokemonType.NORMAL, 100, 70, 20, MoveCategory.PHYSICAL, "Effects vary with terrain."),
    SECRET_SWORD("Secret Sword", PokemonType.FIGHTING, 100, 85, 10, MoveCategory.SPECIAL, "Damage is based on the target's Defense stat."),
    SEED_BOMB("Seed Bomb", PokemonType.GRASS, 100, 80, 15, MoveCategory.PHYSICAL, "No additional effect."),
    SEED_FLARE("Seed Flare", PokemonType.GRASS, 85, 120, 5, MoveCategory.SPECIAL, "40% chance to lower Special Defense by 2 stages."),
    SEISMIC_TOSS("Seismic Toss", PokemonType.FIGHTING, 100, 0, 20, MoveCategory.PHYSICAL, "Does damage equal to the user's level."),
    SELF_DESTRUCT("Self-Destruct", PokemonType.NORMAL, 100, 200, 5, MoveCategory.PHYSICAL, "Faints the user."),
    SHADOW_BALL("Shadow Ball", PokemonType.GHOST, 100, 80, 15, MoveCategory.SPECIAL, "20% chance to lower Special Defense by 1 stage."),
    SHADOW_CLAW("Shadow Claw", PokemonType.GHOST, 100, 70, 15, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    SHADOW_FORCE("Shadow Force", PokemonType.GHOST, 100, 120, 5, MoveCategory.PHYSICAL, "User becomes invulnerable, then attacks the next turn. Nullifies Detect and Protect."),
    SHADOW_PUNCH("Shadow Punch", PokemonType.GHOST, 0, 60, 20, MoveCategory.PHYSICAL, "Ignores accuracy modifiers."),
    SHADOW_SNEAK("Shadow Sneak", PokemonType.GHOST, 100, 40, 30, MoveCategory.PHYSICAL, "The user always attacks first."),
    SHARPEN("Sharpen", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Boosts Attack by 1 stage."),
    SHEER_COLD("Sheer Cold", PokemonType.ICE, 30, 0, 5, MoveCategory.SPECIAL, "Will OHKO the target."),
    SHELL_SMASH("Shell Smash", PokemonType.NORMAL, 0, 0, 15, MoveCategory.NON_DAMAGING, "Boosts user's Attack, Special Attack, and Speed by 2 stages and lowers user's Defense and Special Defense by 1 stage."),
    SHIFT_GEAR("Shift Gear", PokemonType.STEEL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Boosts Speed by 2 stages and Attack by 1 stage."),
    SHOCK_WAVE("Shock Wave", PokemonType.ELECTRIC, 0, 60, 20, MoveCategory.SPECIAL, "Ignores accuracy modifiers."),
    SIGNAL_BEAM("Signal Beam", PokemonType.BUG, 100, 75, 15, MoveCategory.SPECIAL, "10% chance to confuse."),
    SILVER_WIND("Silver Wind", PokemonType.BUG, 100, 60, 5, MoveCategory.SPECIAL, "10% chance to boost all stats by 1 stage."),
    SIMPLE_BEAM("Simple Beam", PokemonType.NORMAL, 100, 0, 15, MoveCategory.NON_DAMAGING, "Changes the target's ability to Simple."),
    SING("Sing", PokemonType.NORMAL, 55, 0, 15, MoveCategory.NON_DAMAGING, "Puts the target to sleep."),
    SKETCH("Sketch", PokemonType.NORMAL, 0, 0, 1, MoveCategory.NON_DAMAGING, "Permanently copies the last move used by the target."),
    SKILL_SWAP("Skill Swap", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "The user and the target trade abilities."),
    SKULL_BASH("Skull Bash", PokemonType.NORMAL, 100, 130, 15, MoveCategory.PHYSICAL, "Charges up turn one; attacks turn two. Boosts Defense by 1 stage."),
    SKY_ATTACK("Sky Attack", PokemonType.FLYING, 90, 140, 5, MoveCategory.PHYSICAL, "Hits the turn after being used."),
    SKY_DROP("Sky Drop", PokemonType.FLYING, 100, 60, 10, MoveCategory.PHYSICAL, "Hits the turn after being used. The target cannot move while in the air."),
    SKY_UPPERCUT("Sky Uppercut", PokemonType.FIGHTING, 90, 85, 15, MoveCategory.PHYSICAL, "Hits a Bouncing or Flying target."),
    SLACK_OFF("Slack Off", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% max HP."),
    SLAM("Slam", PokemonType.NORMAL, 75, 80, 20, MoveCategory.PHYSICAL, "No additional effect."),
    SLASH("Slash", PokemonType.NORMAL, 100, 70, 20, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    SLEEP_POWDER("Sleep Powder", PokemonType.GRASS, 75, 0, 15, MoveCategory.NON_DAMAGING, "Puts the target to sleep."),
    SLEEP_TALK("Sleep Talk", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Picks one of the user's moves at random. Can only be used while sleeping."),
    SLUDGE("Sludge", PokemonType.POISON, 100, 65, 20, MoveCategory.SPECIAL, "30% chance to poison."),
    SLUDGE_BOMB("Sludge Bomb", PokemonType.POISON, 100, 90, 10, MoveCategory.SPECIAL, "30% chance to poison."),
    SLUDGE_WAVE("Sludge Wave", PokemonType.POISON, 100, 95, 10, MoveCategory.SPECIAL, "10% chance to poison the target."),
    SMACK_DOWN("Smack Down", PokemonType.ROCK, 100, 50, 15, MoveCategory.PHYSICAL, "Can hit if target is using Fly, Bounce, or Sky Drop. Ends target's airborne moves and its benefits from Flying type or Levitate."),
    SMELLING_SALTS("Smelling Salts", PokemonType.NORMAL, 100, 70, 10, MoveCategory.PHYSICAL, "Has 120 power on a paralyzed target, but cures it of paralysis."),
    SMOG("Smog", PokemonType.POISON, 70, 30, 20, MoveCategory.SPECIAL, "40% chance to poison."),
    SMOKESCREEN("Smokescreen", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers foe's accuracy by 1 stage."),
    SNARL("Snarl", PokemonType.DARK, 95, 55, 15, MoveCategory.SPECIAL, "Lowers target's Special Attack by 1 stage."),
    SNATCH("Snatch", PokemonType.DARK, 0, 0, 10, MoveCategory.NON_DAMAGING, "If certain moves are used, the user of Snatch uses the moves instead."),
    SNORE("Snore", PokemonType.NORMAL, 100, 50, 15, MoveCategory.SPECIAL, "Can only be used while sleeping. 30% chance to flinch."),
    SOAK("Soak", PokemonType.WATER, 100, 0, 20, MoveCategory.NON_DAMAGING, "Changes the target's type to Water."),
    SOFT_BOILED("Soft-Boiled", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% max HP."),
    SOLAR_BEAM("Solar Beam", PokemonType.GRASS, 100, 120, 10, MoveCategory.SPECIAL, "Charges up turn 1; attacks on turn 2."),
    SONIC_BOOM("Sonic Boom", PokemonType.NORMAL, 90, 0, 20, MoveCategory.SPECIAL, "Does 20 damage. Ghosts are immune."),
    SPACIAL_REND("Spacial Rend", PokemonType.DRAGON, 95, 100, 5, MoveCategory.SPECIAL, "Has a high critical hit rate."),
    SPARK("Spark", PokemonType.ELECTRIC, 100, 65, 20, MoveCategory.PHYSICAL, "30% chance to paralyze."),
    SPIDER_WEB("Spider Web", PokemonType.BUG, 0, 0, 10, MoveCategory.NON_DAMAGING, "The target cannot switch out."),
    SPIKE_CANNON("Spike Cannon", PokemonType.NORMAL, 100, 20, 15, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    SPIKES("Spikes", PokemonType.GROUND, 0, 0, 20, MoveCategory.NON_DAMAGING, "Causes damage to the enemy whenever they switch."),
    SPIKY_SHIELD("Spiky Shield", PokemonType.GRASS, 0, 0, 10, MoveCategory.NON_DAMAGING, "In addition to protecting the user from attacks, this move also damages any attacker who makes direct contact by 1/8 of their maximum HP."),
    SPIT_UP("Spit Up", PokemonType.NORMAL, 100, 0, 10, MoveCategory.SPECIAL, "Varies in power depending on the number of uses of Stockpile."),
    SPITE("Spite", PokemonType.GHOST, 100, 0, 10, MoveCategory.NON_DAMAGING, "Lowers the PP of the move used last by 1-5."),
    SPLASH("Splash", PokemonType.NORMAL, 0, 0, 40, MoveCategory.NON_DAMAGING, "No effect whatsoever."),
    SPORE("Spore", PokemonType.GRASS, 100, 0, 15, MoveCategory.NON_DAMAGING, "Puts the target to sleep."),
    STEALTH_ROCK("Stealth Rock", PokemonType.ROCK, 0, 0, 20, MoveCategory.NON_DAMAGING, "Damages foe's switch-ins."),
    STEAM_ERUPTION("Steam Eruption", PokemonType.WATER, 95, 110, 5, MoveCategory.SPECIAL, "30% chance to burn the target."),
    STEAMROLLER("Steamroller", PokemonType.BUG, 100, 65, 20, MoveCategory.PHYSICAL, "Has a 30% chance to flinch the target."),
    STEEL_WING("Steel Wing", PokemonType.STEEL, 90, 70, 25, MoveCategory.PHYSICAL, "10% chance to raise the user's Defense by 1 stage."),
    STICKY_WEB("Sticky Web", PokemonType.BUG, 0, 0, 20, MoveCategory.NON_DAMAGING, "Lowers the Speed stat of the opposing team's Pokemon upon switching into battle."),
    STOCKPILE("Stockpile", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Sets the user up to use Spit Up and Swallow."),
    STOMP("Stomp", PokemonType.NORMAL, 100, 65, 20, MoveCategory.PHYSICAL, "30% chance to flinch."),
    STONE_EDGE("Stone Edge", PokemonType.ROCK, 80, 100, 5, MoveCategory.PHYSICAL, "Has a high critical hit rate."),
    STORED_POWER("Stored Power", PokemonType.PSYCHIC, 100, 20, 10, MoveCategory.SPECIAL, "Varies in power depending on number of boosts accumulated by user."),
    STORM_THROW("Storm Throw", PokemonType.FIGHTING, 100, 60, 10, MoveCategory.PHYSICAL, "Always results in a critical hit."),
    STRENGTH("Strength", PokemonType.NORMAL, 100, 80, 15, MoveCategory.PHYSICAL, "No additional effect."),
    STRING_SHOT("String Shot", PokemonType.BUG, 95, 0, 40, MoveCategory.NON_DAMAGING, "Lowers foe's Speed 1 stage."),
    STRUGGLE("Struggle", PokemonType.NORMAL, 0, 50, 1, MoveCategory.PHYSICAL, "Has 1/2 recoil."),
    STRUGGLE_BUG("Struggle Bug", PokemonType.BUG, 100, 50, 20, MoveCategory.SPECIAL, "Lowers target's Special Attack by 1 stage."),
    STUN_SPORE("Stun Spore", PokemonType.GRASS, 75, 0, 30, MoveCategory.NON_DAMAGING, "Paralyzes the target."),
    SUBMISSION("Submission", PokemonType.FIGHTING, 80, 80, 25, MoveCategory.PHYSICAL, "Has 1/4 recoil."),
    SUBSTITUTE("Substitute", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Takes 1/4 the user's max HP to create a Substitute that takes damage for the user."),
    SUCKER_PUNCH("Sucker Punch", PokemonType.DARK, 100, 80, 5, MoveCategory.PHYSICAL, "The user always moves first. Will only work if the foe attacked."),
    SUNNY_DAY("Sunny Day", PokemonType.FIRE, 0, 0, 5, MoveCategory.NON_DAMAGING, "Summons sun for 5 turns."),
    SUPER_FANG("Super Fang", PokemonType.NORMAL, 90, 0, 10, MoveCategory.PHYSICAL, "Does damage equal to half the foe's current HP."),
    SUPERPOWER("Superpower", PokemonType.FIGHTING, 100, 120, 5, MoveCategory.PHYSICAL, "Lowers the user's Attack and Defense by 1 stage."),
    SUPERSONIC("Supersonic", PokemonType.NORMAL, 55, 0, 20, MoveCategory.NON_DAMAGING, "Confuses the foe."),
    SURF("Surf", PokemonType.WATER, 100, 90, 15, MoveCategory.SPECIAL, "No additional effect."),
    SWAGGER("Swagger", PokemonType.NORMAL, 90, 0, 15, MoveCategory.NON_DAMAGING, "Confuses the target. Boosts its Attack by 2 stages."),
    SWALLOW("Swallow", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Healing varies based on the number of uses of Stockpile."),
    SWEET_KISS("Sweet Kiss", PokemonType.FAIRY, 75, 0, 10, MoveCategory.NON_DAMAGING, "Confuses the target."),
    SWEET_SCENT("Sweet Scent", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers evasion by 1 stage."),
    SWIFT("Swift", PokemonType.NORMAL, 0, 60, 20, MoveCategory.SPECIAL, "Always hits."),
    SWITCHEROO("Switcheroo", PokemonType.DARK, 100, 0, 10, MoveCategory.NON_DAMAGING, "Switches items with the target."),
    SWORDS_DANCE("Swords Dance", PokemonType.NORMAL, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Attack by 2 stages."),
    SYNCHRONOISE("Synchronoise", PokemonType.PSYCHIC, 100, 120, 15, MoveCategory.SPECIAL, "Only damages targets of the same type as the user."),
    SYNTHESIS("Synthesis", PokemonType.GRASS, 0, 0, 5, MoveCategory.NON_DAMAGING, "Heals variably depending on the weather."),
    TACKLE("Tackle", PokemonType.NORMAL, 100, 50, 35, MoveCategory.PHYSICAL, "No additional effect."),
    TAIL_GLOW("Tail Glow", PokemonType.BUG, 0, 0, 20, MoveCategory.NON_DAMAGING, "Boosts Special Attack by 2 stages."),
    TAIL_SLAP("Tail Slap", PokemonType.NORMAL, 85, 25, 10, MoveCategory.PHYSICAL, "Hits 2-5 times in one turn."),
    TAIL_WHIP("Tail Whip", PokemonType.NORMAL, 100, 0, 30, MoveCategory.NON_DAMAGING, "Lowers foe's Defense by 1 stage."),
    TAILWIND("Tailwind", PokemonType.FLYING, 0, 0, 30, MoveCategory.NON_DAMAGING, "Doubles Speed for 3 turns."),
    TAKE_DOWN("Take Down", PokemonType.NORMAL, 85, 90, 20, MoveCategory.PHYSICAL, "Has 1/4 recoil."),
    TAUNT("Taunt", PokemonType.DARK, 100, 0, 20, MoveCategory.NON_DAMAGING, "Forces the foe to use damaging moves for 2 turns."),
    TECHNO_BLAST("Techno Blast", PokemonType.NORMAL, 100, 120, 5, MoveCategory.SPECIAL, "Type will change depending on the type of Drive."),
    TEETER_DANCE("Teeter Dance", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Confuses all other active Pokemon."),
    TELEKINESIS("Telekinesis", PokemonType.PSYCHIC, 0, 0, 15, MoveCategory.NON_DAMAGING, "Lasts 3 turns and makes all moves hit the target.  Makes target immune to Ground-type moves."),
    TELEPORT("Teleport", PokemonType.PSYCHIC, 0, 0, 20, MoveCategory.NON_DAMAGING, "Has no effect."),
    THIEF("Thief", PokemonType.DARK, 100, 60, 25, MoveCategory.PHYSICAL, "Steals target's item."),
    THOUSAND_ARROWS("Thousand Arrows", PokemonType.GROUND, 100, 90, 10, MoveCategory.PHYSICAL, "Hits Pokemon in the air and knocks them to the ground."),
    THOUSAND_WAVES("Thousand Waves", PokemonType.GROUND, 100, 90, 10, MoveCategory.PHYSICAL, "Prevents affected Pokemon from switching."),
    THRASH("Thrash", PokemonType.NORMAL, 100, 120, 10, MoveCategory.PHYSICAL, "Repeats for 2-3 turns. Confuses the user."),
    THUNDER("Thunder", PokemonType.ELECTRIC, 70, 110, 10, MoveCategory.SPECIAL, "30% chance to paralyze."),
    THUNDER_FANG("Thunder Fang", PokemonType.ELECTRIC, 95, 65, 15, MoveCategory.PHYSICAL, "10% chance to flinch. 10% chance to paralyze."),
    THUNDER_PUNCH("Thunder Punch", PokemonType.ELECTRIC, 100, 75, 15, MoveCategory.PHYSICAL, "10% chance to paralyze."),
    THUNDER_SHOCK("Thunder Shock", PokemonType.ELECTRIC, 100, 40, 30, MoveCategory.SPECIAL, "10% chance to paralyze."),
    THUNDER_WAVE("Thunder Wave", PokemonType.ELECTRIC, 100, 0, 20, MoveCategory.NON_DAMAGING, "Paralyzes the foe."),
    THUNDERBOLT("Thunderbolt", PokemonType.ELECTRIC, 100, 90, 15, MoveCategory.SPECIAL, "10% chance to paralyze."),
    TICKLE("Tickle", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers Attack and Defense by 1 stage."),
    TOPSY_TURVY("Topsy-Turvy", PokemonType.DARK, 0, 0, 20, MoveCategory.NON_DAMAGING, "Inverts target's stat stages."),
    TORMENT("Torment", PokemonType.DARK, 100, 0, 15, MoveCategory.NON_DAMAGING, "Prevents the target from using the same move twice in a row."),
    TOXIC("Toxic", PokemonType.POISON, 90, 0, 10, MoveCategory.NON_DAMAGING, "Inflicts intensifying poison on the target."),
    TOXIC_SPIKES("Toxic Spikes", PokemonType.POISON, 0, 0, 20, MoveCategory.NON_DAMAGING, "Poisons opponents as they switch switch in."),
    TRANSFORM("Transform", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Transforms into the foe."),
    TRI_ATTACK("Tri Attack", PokemonType.NORMAL, 100, 80, 10, MoveCategory.SPECIAL, "20% chance to burn, freeze, or paralyze."),
    TRICK("Trick", PokemonType.PSYCHIC, 100, 0, 10, MoveCategory.NON_DAMAGING, "Switches items with the foe."),
    TRICK_ROOM("Trick Room", PokemonType.PSYCHIC, 0, 0, 5, MoveCategory.NON_DAMAGING, "Slower Pokemon move first for 5 turns."),
    TRICK_OR_TREAT("Trick-or-Treat", PokemonType.GHOST, 100, 0, 20, MoveCategory.NON_DAMAGING, "Adds Ghost to the target's type(s). If the target already has three types, the third is replaced."),
    TRIPLE_KICK("Triple Kick", PokemonType.FIGHTING, 90, 10, 10, MoveCategory.PHYSICAL, "Attacks up to 3 times in 1 turn."),
    TRUMP_CARD("Trump Card", PokemonType.NORMAL, 0, 0, 5, MoveCategory.SPECIAL, "Power increases as PP decreases."),
    TWINEEDLE("Twineedle", PokemonType.BUG, 100, 25, 20, MoveCategory.PHYSICAL, "Hits twice in one turn. Each hit has a 20% chance to poison."),
    TWISTER("Twister", PokemonType.DRAGON, 100, 40, 20, MoveCategory.SPECIAL, "20% chance to flinch."),
    U_TURN("U-turn", PokemonType.BUG, 100, 70, 20, MoveCategory.PHYSICAL, "Attacks, then switches."),
    UPROAR("Uproar", PokemonType.NORMAL, 100, 90, 10, MoveCategory.SPECIAL, "Repeats for 2-5 turns. No Pokemon can sleep during these turns."),
    V_CREATE("V-create", PokemonType.FIRE, 95, 180, 5, MoveCategory.PHYSICAL, "Lowers user's Defense, Special Defense, and Speed by 1 stage."),
    VACUUM_WAVE("Vacuum Wave", PokemonType.FIGHTING, 100, 40, 30, MoveCategory.SPECIAL, "The user always attacks first."),
    VENOM_DRENCH("Venom Drench", PokemonType.POISON, 100, 0, 20, MoveCategory.NON_DAMAGING, "Lowers the Attack, Special Attack, and Speed stats of a poisoned target."),
    VENOSHOCK("Venoshock", PokemonType.POISON, 100, 65, 10, MoveCategory.SPECIAL, "Hits poisoned targets with double Base Power."),
    VICE_GRIP("Vice Grip", PokemonType.NORMAL, 100, 55, 30, MoveCategory.PHYSICAL, "No additional effect."),
    VINE_WHIP("Vine Whip", PokemonType.GRASS, 100, 45, 15, MoveCategory.PHYSICAL, "No additional effect."),
    VITAL_THROW("Vital Throw", PokemonType.FIGHTING, 0, 70, 10, MoveCategory.PHYSICAL, "Moves second, but ignores accuracy modifiers."),
    VOLT_SWITCH("Volt Switch", PokemonType.ELECTRIC, 100, 70, 20, MoveCategory.SPECIAL, "Forces user to switch."),
    VOLT_TACKLE("Volt Tackle", PokemonType.ELECTRIC, 100, 120, 15, MoveCategory.PHYSICAL, "Has 1/3 recoil."),
    WAKE_UP_SLAP("Wake-Up Slap", PokemonType.FIGHTING, 100, 70, 10, MoveCategory.PHYSICAL, "Double Base Power if used on a sleeping foe."),
    WATER_GUN("Water Gun", PokemonType.WATER, 100, 40, 25, MoveCategory.SPECIAL, "No additional effect."),
    WATER_PLEDGE("Water Pledge", PokemonType.WATER, 100, 80, 10, MoveCategory.SPECIAL, "Use with Fire Pledge and Grass Pledge for additional effect."),
    WATER_PULSE("Water Pulse", PokemonType.WATER, 100, 60, 20, MoveCategory.SPECIAL, "20% chance to confuse."),
    WATER_SHURIKEN("Water Shuriken", PokemonType.WATER, 100, 15, 20, MoveCategory.PHYSICAL, "Deals damage to one adjacent target and hits two to five times. Has a 1/3 chance to hit two or three times, and a 1/6 chance to hit four or five times. If one of the hits breaks the target's Substitute, it will take damage for the remaining hits. If the user has the Ability Skill Link, this move will always hit five times. Almost always goes first."),
    WATER_SPORT("Water Sport", PokemonType.WATER, 0, 0, 15, MoveCategory.NON_DAMAGING, "Fire-type attacks do 50% damage."),
    WATER_SPOUT("Water Spout", PokemonType.WATER, 100, 150, 5, MoveCategory.SPECIAL, "Does less damage as the user's HP decreases."),
    WATERFALL("Waterfall", PokemonType.WATER, 100, 80, 15, MoveCategory.PHYSICAL, "No additional effect."),
    WEATHER_BALL("Weather Ball", PokemonType.NORMAL, 100, 50, 10, MoveCategory.SPECIAL, "Doubles in power and changes type if there is weather."),
    WHIRLPOOL("Whirlpool", PokemonType.WATER, 85, 35, 15, MoveCategory.SPECIAL, "Traps and damages target for 4-5 turns."),
    WHIRLWIND("Whirlwind", PokemonType.NORMAL, 100, 0, 20, MoveCategory.NON_DAMAGING, "Forces the target to switch to a random Pokemon."),
    WIDE_GUARD("Wide Guard", PokemonType.ROCK, 0, 0, 10, MoveCategory.NON_DAMAGING, "Protects user and allies from multi-target attacks."),
    WILD_CHARGE("Wild Charge", PokemonType.ELECTRIC, 100, 90, 15, MoveCategory.PHYSICAL, "Has 1/4 recoil."),
    WILL_O_WISP("Will-O-Wisp", PokemonType.FIRE, 85, 0, 15, MoveCategory.NON_DAMAGING, "Burns the foe."),
    WING_ATTACK("Wing Attack", PokemonType.FLYING, 100, 60, 35, MoveCategory.PHYSICAL, "No additional effect."),
    WISH("Wish", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Heals 50% of max HP after 2 turns."),
    WITHDRAW("Withdraw", PokemonType.WATER, 0, 0, 40, MoveCategory.NON_DAMAGING, "Boosts Defense by 1 stage."),
    WONDER_ROOM("Wonder Room", PokemonType.PSYCHIC, 0, 0, 10, MoveCategory.NON_DAMAGING, "Swaps Defense and Special Defense of all Pokemon."),
    WOOD_HAMMER("Wood Hammer", PokemonType.GRASS, 100, 120, 15, MoveCategory.PHYSICAL, "Has 1/3 recoil."),
    WORK_UP("Work Up", PokemonType.NORMAL, 0, 0, 30, MoveCategory.NON_DAMAGING, "Boosts user's Attack and Special Attack by 1 stage."),
    WORRY_SEED("Worry Seed", PokemonType.GRASS, 100, 0, 10, MoveCategory.NON_DAMAGING, "Changes the foe's ability to Insomnia."),
    WRAP("Wrap", PokemonType.NORMAL, 90, 15, 20, MoveCategory.PHYSICAL, "Prevents the opponent from attacking for 2-5 turns."),
    WRING_OUT("Wring Out", PokemonType.NORMAL, 100, 0, 5, MoveCategory.SPECIAL, "Base power depends on the foe's remaining HP."),
    X_SCISSOR("X-Scissor", PokemonType.BUG, 100, 80, 15, MoveCategory.PHYSICAL, "No additional effect."),
    YAWN("Yawn", PokemonType.NORMAL, 0, 0, 10, MoveCategory.NON_DAMAGING, "Puts the target to sleep after 2 turns."),
    ZAP_CANNON("Zap Cannon", PokemonType.ELECTRIC, 50, 120, 5, MoveCategory.SPECIAL, "Paralyzes the foe."),
    ZEN_HEADBUTT("Zen Headbutt", PokemonType.PSYCHIC, 90, 80, 15, MoveCategory.PHYSICAL, "20% chance to flinch.");

    private final int accuracy, power, pp;
    private final PokemonType type;
    private final String name, description;
    private final MoveCategory category;

    Move(String name, PokemonType type, int accuracy, int power, int pp,
                MoveCategory category, String description) {
        this.name = name;
        this.description = description;
        this.accuracy = accuracy;
        this.power = power;
        this.pp = pp;
        this.type = type;
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public int getAccuracy() {
        return accuracy;
    }

    public int getPower() {
        return power;
    }

    public int getPp() {
        return pp;
    }

    public PokemonType getType() {
        return type;
    }

    public MoveCategory getCategory() {
        return category;
    }

    public String toString() {
        return name;
    }
}
